### ISSUE TITLE
Notification icon in the menu shows all the time unless you configure all services.

### ISSUE THREAD

**Issue by eflorea** [10up/classifai#100]
**Describe the bug**

Notification icon in the Admin Menu shows all the time unless you configure all the services.

**Steps to Reproduce**

1. Configure only Image Processing settings
2. Notification still shows and it's confusing feels like something is requiring attention but in reality no - maybe I don't want to use Language Processing.

**Screenshots**

![Screen Shot 2019-07-12 at 10 24 53 AM](https://user-images.githubusercontent.com/13055601/61146815-c130f300-a48f-11e9-90fc-a40d5b2f7ede.png)

**Comment by jeffpaul** [comment]
@eflorea thanks for the feedback, would happily review a PR to resolve this, but otherwise have milestoned this to get resolved in an upcoming release.

**Comment by helen** [comment]
Since this will be more involved as more providers are added, I think maybe it's better if we either remove it for now and revisit holistically later, or tie it to having a valid registration key instead. Thoughts/preferences?

**Comment by jeffpaul** [comment]
After discussing with @helen, let's reduce this to just be an alert when no reg key has been set.  We want folks to have ClassifAI updates available to them based on all the great stuff on the roadmap, so prompting them to complete that step seems worthwhile.  It doesn't seem necessary to continue to alert them if any of the services are unconfigured as they're likely to figure that out if they're not seeing tagging/alt-text/etc.
