### ISSUE TITLE
Service not configured/enabled triggers errors

### ISSUE THREAD

**Issue by eflorea** [10up/classifai#102]
**Describe the bug**

I don't have language processing configured and none of the Post Types to Classify are checked under the settings wp-admin/admin.php?page=language_processing
![Screen Shot 2019-07-23 at 12 08 05 PM](https://user-images.githubusercontent.com/13055601/61740053-94f45c80-ad42-11e9-8b93-2077c2a9a583.png)

but the plugin still tries to classify them when updating a post and it throws a notice:
 
![Screen Shot 2019-07-23 at 12 05 14 PM](https://user-images.githubusercontent.com/13055601/61740021-7bebab80-ad42-11e9-8126-d0222ae4e967.png)

**Steps to Reproduce**

1. Install Plugin and register plugin for update notification
2. Configure Image Processing
3. Do not configure Language Processing
4. Add/Update any post
5. See error from the above screenshot.

**Expected behavior**

If Language Processing is not configured there shouldn't be any requests to the Watson API.

**Comment by jeffpaul** [comment]
@eflorea thanks for the report, we're working to test other scenarios to see if this notice gets incorrectly thrown in other places, but are otherwise working on a fix for this and intend to include it in our next targeted minor release (v1.3.2).

**Comment by jeffpaul** [comment]
@eflorea can you confirm the page that you're seeing that notice appear on?  In my testing its showing on wp-admin/edit.php and wanted to see if that matches what you're seeing.

**Comment by eflorea** [comment]
@jeffpaul I haven't seen it in edit.php but when you add/update a post so URL would look like: wp-admin/post.php?post=XXX&action=edit

**Comment by jeffpaul** [comment]
@eflorea yep, just tested a post update and am seeing it on wp-admin/post.php?post=XXX&action=edit as well.  Looks like post add only appears when you go back to the post list table view though.

**Comment by jeffpaul** [comment]
Looks like the error shown within Gutenberg upon editing a post is:
`Failed to classify content with the IBM Watson NLU API. Error: http_request_failed - A valid URL was not provided.`

So essentially the same thing, just a little different ordering of the test.

**Comment by jeffpaul** [comment]
The error show within the Classic Editor on post add and post update matches that shown on wp-admin/edit.php, namely:
`Error: Failed to classify content with the IBM Watson NLU API.`
`http_request_failed - A valid URL was not provided. `

**Comment by jeffpaul** [comment]
My testing also shows that if you properly add the Language Processing settings the errors go away.  Clearing those Language Processing settings causes the errors to re-appear on post add and post update.
