### ISSUE TITLE
Integrate Azure Computer Vision for smart image cropping

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#112]
**Is your enhancement related to a problem? Please describe.**
Azure's [Computer Vision](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/computervision/generatethumbnail/generatethumbnail) is able to use smart cropping when generating thumbnails for images.  This could be useful on sites utilizing images that don't always crop "nicely" via existing image size generation scripts.  Smart cropping ensures that the most relevant parts of your uploaded image are retained on the various image sizes generated.

**Describe the solution you'd like**
If this concept gains positive feedback, then we'll want to iterate on it to build out more specific requirements before we dive into development on this.

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by johnwatkins0** [comment]
@jeffpaul If it's OK, I'd like to work on this issue. @Ritesh-patel has shared a prototype that does cropping with Computer Vision that looks like it will be a great starting point.

**Comment by jeffpaul** [comment]
@johnwatkins0 sounds great!  That's the core feature for the next major release (v1.5), so please do call out if you need help or have questions on this.

**Comment by jeffpaul** [comment]
Some cropping-related feedback to consider as it relates to updates to the cropping functionality within core: https://core.trac.wordpress.org/ticket/30155
