### ISSUE TITLE
Integrate Azure Video Indexer to generate closed captioning files

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#113]
**Is your enhancement related to a problem? Please describe.**
Azure's [Video Indexer](https://docs.microsoft.com/en-us/azure/media-services/video-indexer/video-indexer-overview) is able to generate VTT, TTML, and SRT closed captioning files for video/audio segments which would assist with accessibility improvements for video/audio files.  For people leveraging YouTube/Vimeo/etc. for their video content, this may not be relevant.  For folks using other video hosting options, this may be of use to them ([VideoPress](https://videopress.com/) comes to mind here).

**Describe the solution you'd like**
If this concept gains positive feedback, then we'll want to iterate on it to build out more specific requirements before we dive into development on this.

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jeffpaul** [comment]
This feature could tie into the new [video block subtitles](https://github.com/WordPress/gutenberg/pull/25861) added in [Gutenberg 9.2](https://make.wordpress.org/core/2020/10/21/whats-new-in-gutenberg-21-october/) such that ClassifAI automatically generates subtitles when a video is added and includes that output in the subtitle as a VTT file.

**Comment by jeffpaul** [comment]
Related article: "[Did You Know? Audio Description Is Required by Law](https://www.3playmedia.com/blog/did-you-know-audio-description-is-required-by-law/)"
> "Private and public colleges that receive federal funding must comply with the Rehabilitation Act. Colleges that receive state funding must comply with local state laws, too (often called mini-508s). All colleges provide a public accommodation and must comply with ADA requirements."

**Comment by Sidsector9** [comment]
@jeffpaul I was wondering, seeing that browsers have started implementing live captions natively and may add support for more languages, would adding this feature be viable for the long run in terms of the value it adds?

**Comment by jeffpaul** [comment]
@Sidsector9 can you provide an example of a browser adding that functionality?  I've not yet seen that and would (1) be super interested to test/use personally and (2) probably be sufficient cause to close this issue.

**Comment by Sidsector9** [comment]
@jeffpaul This is Chrome's accessibility feature to generate live captions: https://support.google.com/chrome/answer/10538231?hl=en

This is a demo - https://youtube.com/shorts/KDP8a5s8yaU?feature=share

**Comment by jeffpaul** [comment]
Oh wow, that's pretty slick, hopefully other browsers (ahem Firefox ahem) will do the same!
