### ISSUE TITLE
Integrate Azure Text to Speech for "read-to-me" functionality on blog posts

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#115]
**Is your enhancement related to a problem? Please describe.**
Azure's [Text to Speech](https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/) is able to convert text to audio in near real time, play it back, and save it as a file for later use.  This could be leveraged to assist with accessibility improvements for text-only/text-heavy content so that it could be available as audio content.

**Describe the solution you'd like**
If this concept gains positive feedback, then we'll want to iterate on it to build out more specific requirements before we dive into development on this.

**Designs**
n/a

**Describe alternatives you've considered**
This functionality exists via AWS Labs and WP Engine's [Amazon Polly plugin](https://wordpress.org/plugins/amazon-polly/), but would mimic that utilizing Azure instead of AWS.

**Additional context**
none

**Comment by jeffpaul** [comment]
[Latest update from Azure](https://azure.microsoft.com/en-us/updates/cognitive-services-speech-adds-new-neural-tts-voices-and-ga-of-neural-tts-in-containers/) adds 5 additional languages for a total of 54 languages/locales with 73 neural voices and 77 standard voices available.

**Comment by jeffpaul** [comment]
[Latest update from Azure](https://azure.microsoft.com/en-us/updates/general-availability-custom-neural-voice-a-custom-texttospeech-capability-within-speech-service/) brings totals to [129 neural voices](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fcognitive-services%2Fspeech-service%2Flanguage-support%23neural-voices&data=04%7C01%7Cwmendoza%40microsoft.com%7C68f676a1366349b1fe1a08d887704bb8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637408263841622128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8lKFPjlZXg61bWl7%2FNHfLysUWkeeeLxRKubo%2FKZrQAI%3D&reserved=0) and [77 standard voices ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fcognitive-services%2Fspeech-service%2Flanguage-support%23standard-voices&data=04%7C01%7Cwmendoza%40microsoft.com%7C68f676a1366349b1fe1a08d887704bb8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637408263841632126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6c1SLCWJpDcCMmnn57kjefN2bwfFPc0DtOaJ9Ufh9Jk%3D&reserved=0)across 54 languages/locales plus the ability to [create a custom neural voice](https://aka.ms/customneural) (currently still needs Azure approval even though this is in GA).

**Comment by jeffpaul** [comment]
For what its worth, [Watson also has a Text to Speech function](https://www.ibm.com/cloud/watson-text-to-speech) that could be a good option to compare to Azure to see which might be the "best" service to build into ClassifAI for this.  Same with [Amazon Polly](https://aws.amazon.com/polly/) as an option here.

**Comment by pixeldevsio** [comment]
I think going with Watson is the smart choice since we integrate with it already. They both offer different languages and the speed between their translations seems negligible at best.

**Comment by jeffpaul** [comment]
@pixeldevsio seems reasonable to me, are you able to work on that as a PR or should I look to someone else to help step in there?

**Comment by pixeldevsio** [comment]
I can work on it. I have some time in the coming weeks.

**Comment by pixeldevsio** [comment]
so far we’re generating an mp3 file from the Watson API.
TODO:

- Hook up an individual post option to turn the audio on (default to off)
- Hook into the save_post and generate audio files when needed
- Come up with a storage/naming convention for the audio files
- Create a block to display the audio file
- Miscellaneous fixes and testing
