### ISSUE TITLE
Docs: note image processing won't work on local env

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#124]
**Is your enhancement related to a problem? Please describe.**
The following docs update came in from someone who signed up on classifaiplugin.com. Image Processing (via Azure Computer Vision) won't work on local environments as it requires the image to be accessible externally via the internet.

**Describe the solution you'd like**
- [ ] update the [docs](https://github.com/10up/classifai#set-up-image-processing-via-microsoft-azure) in the readme to note that this won't work on a local environment

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jeffpaul** [comment]
Note from @ryanwelcher that you can use the following mu-plugin that redirects local requests to an online image, its a filter but will help when testing ClassifAI image processing locally.  

>add_filter(
>    'wp_get_attachment_image_src',
>    function( $image ) {
>        $image[0] = 'https://10up.com/uploads/2018/12/Final_final_final_2018_card.jpg';
>        return $image;
>    }
>);

Potential tweak to this as @helen noted would be to pull a random image instead of the same one every time (e.g., [Unsplash](https://source.unsplash.com/)).

**Comment by ryanwelcher** [comment]
@jeffpaul @helen randomizing the image might be tricky to test with - depending on what kind of results we need. I tried something similar and it became hard to debug thresholds etc if the image is different every time. If we're just testing that we get results, it should be fine.
