### ISSUE TITLE
Azure Computer Vision error messaging on null matches

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#139]
**Is your enhancement related to a problem? Please describe.**
Expand upon the work done in #75 and continue to add features from Computer Vision.

**Describe the solution you'd like**
- [ ] error messaging or hook available to catch when ClassifAI doesn't match something for an image's alt text

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Split out from #75

**Comment by jeffpaul** [comment]
As we're looking to release v1.5.0 in the next week or so and with no linked PR for this issue, I'm going to move this to `1.6.0` until we're able to work up a PR for it.

**Comment by mustafauysal** [comment]
@jeffpaul  It seemed this issue has been addressed in 5d5e8157764118b9d0be4ef818ce6239db1dc49d

Should we print out some error messages when `classifai_computer_vision_caption_failed` fires?

**Comment by jeffpaul** [comment]
@ryanwelcher do you feel that the work in #125 covered this issue?

**Comment by ryanwelcher** [comment]
@jeffpaul there are two hooks related to computer vision added in 1.5:

`classifai_computer_vision_caption_failed` - fired when no captions are returned
`classifai_computer_vision_image_tag_failed` - fired when no tags are added.

I think we're good to close this issue.

**Comment by jeffpaul** [comment]
@ryanwelcher one extension of this that I was considering was displaying some sort of messaging when alt-text and tags are NOT applied to images.  Maybe something underneath the alt-text field and image tags noting "ClassifAI did not identify any alt-text for this image, considering adjusting your threshold lower to get results back from ClassifAI processing."?
