### ISSUE TITLE
Azure Computer Vision automated captions

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#140]
**Is your enhancement related to a problem? Please describe.**
Expand upon the work done in #75 and continue to add features from Computer Vision.

**Describe the solution you'd like**
- [ ] Automated captions

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Split out from #75

**Comment by Sidsector9** [comment]
@jeffpaul This is similar to https://github.com/10up/classifai/issues/141#issuecomment-1186248741
