### ISSUE TITLE
Azure Computer Vision automated descriptions

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#141]
**Is your enhancement related to a problem? Please describe.**
Expand upon the work done in #75 and continue to add features from Computer Vision.

**Describe the solution you'd like**
- [ ] Automated descriptions

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Split out from #75

**Comment by Sidsector9** [comment]
@jeffpaul the plugin already uses the `description.captions[0].text` value from the response for the alt-text for images. 

I couldn't find a service in the [Image Analysis documentation](https://docs.microsoft.com/en-in/azure/cognitive-services/computer-vision/index-image-analysis) that can provide additional description for an image.

WordPress image description field is analogous to the post content field for a post, and it would be like generating an entire post for the image, which seems to be beyond the capabilities of the Vision API.
