### ISSUE TITLE
Add custom modeling to Image Processing

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#147]
**Is your enhancement related to a problem? Please describe.**
We currently utilize [Azure's Computer Vision](https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/) for the Image Processing functionality, but you're forced to accept what the general Computer Vision model has learned to get feedback in the form of alt text and tags.  A parallel option could be to utilize the [Custom Vision service](https://azure.microsoft.com/en-us/services/cognitive-services/custom-vision-service/) and further train that model to be site-specific.  This would seem to provide a more precise set of image processing results unique to a specific site, though a downside could be pricing of [Custom Vision](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/custom-vision-service/) compared to [Computer Vision](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/computer-vision/).

**Describe the solution you'd like**
- [ ] setting to enable Custom Vision instead of Computer Vision
- [ ] if user edits tags or alt text for an image, send that data back to Custom Vision to further train the model

**Designs**
n/a

**Describe alternatives you've considered**
Keep ClassifAI as-is with Computer Vision and instead work to add additional functionality instead of more complex functionality as described here.

**Additional context**
n/a

**Comment by Sidsector9** [comment]
I researched on this topic today. The use case of training a custom model for images is few and limited.
Training and improving a model for Custom Vision mainly depends on Data quantity, Data balance and Data variety which can be found in systems that have inventories, such as e-commerce sites, etc.

Microsoft [recommends](https://learn.microsoft.com/en-gb/azure/cognitive-services/custom-vision-service/getting-started-improving-your-classifier#data-quantity) 50 images per label as a starting point. These 50 images need to have variety in terms of different angles, backgrounds, object size and groups (which is not a characteristic of blogging/news/tech sites).

It is important to figure out what kind of sites will use such a feature where they will upload 50 images (including variations) of an Apple (for example) as a starting point.

> Depending on the complexity of the problem and degree of accuracy required, hundreds or thousands of samples may be required for your final model. - Custom Vision FAQ

Secondly, Custom Vision requires you to add labels and also tell Vision where the object is in the image. This seems to me like a lot of work per image.

Lastly, if we introduce this feature, we will have to train the customers about the don/don't and the how-to train the model.
[Overfitting](https://learn.microsoft.com/en-gb/azure/cognitive-services/custom-vision-service/getting-started-improving-your-classifier#prevent-overfitting), data [imbalance](https://learn.microsoft.com/en-gb/azure/cognitive-services/custom-vision-service/getting-started-improving-your-classifier#data-balance) and wrong inputs in general can yield incorrect results.

cc: @10up/open-source-practice

**Comment by jeffpaul** [comment]
Fair enough, closing as an unlikely feature to be added.
