### ISSUE TITLE
CLI Script to Smart-Crop existing images

### ISSUE THREAD

**Issue by johnwatkins0** [10up/classifai#176]
**Is your enhancement related to a problem? Please describe.**

After the Smart Cropping PR (#149) is merged, I would expect many site owners to want to apply the feature retroactively. There won't be an easy way to do that immediately, so we should follow up with a CLI script to process existing images. 

**Describe the solution you'd like**

A simple CLI script to process existing images. 

**Designs**

One challenge will be that each image requires its own request to the Azure API, so processing thousands of images at once is probably not an option.

**Describe alternatives you've considered**

It might be better to provide this feature through the Admin UI. Or perhaps both could exist.

**Additional context**

**Comment by sudar** [comment]
@jeffpaul 

I am interested in working on this issue.
