### ISSUE TITLE
Submit 1.5.0 to VIP for review

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#182]
**Is your enhancement related to a problem? Please describe.**
We'll want to ensure that any one on WordPress VIP are able to use ClassifAI, but we're not currently certain that's the case.

**Describe the solution you'd like**
Submit ClassifAI for VIP review and work to resolve any issues identified within a quickly following release.

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by jeffpaul** [comment]
@ryanwelcher I'm not certain if we're able to submit this to VIP for review or if it needs to come from a project team working with VIP, but either way I figure we can run ClassifAI through the VIP coding standards to see what pops up to look into resolving perhaps?

**Comment by ryanwelcher** [comment]
@jeffpaul I've run the 1.5.1 release though phpcs and there are some items that will need to be addressed. I'll start a PR with the changes.

**Comment by jeffpaul** [comment]
@dinhtungdu probably worthwhile updating the Linting action to also run VIPCS to help close out this task for 1.7.0.
