### ISSUE TITLE
Add live preview of results for threshold settings

### ISSUE THREAD

**Issue by helen** [10up/classifai#193]
**Is your enhancement related to a problem? Please describe.**
Adjusting the thresholds for various types of classifications is a game of save-and-surprise, and you have to save both the settings *and* go to update/add a post or image.

**Describe the solution you'd like**
I would like a previewer in the settings screen where you can try out thresholds with a piece of your content and possibly also a piece of test content we could include. This would allow you to see how fuzzy results do or don't get with the type of content you're handling. The [Azure examples](https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/#features) are a pretty good reference, except that I would want to show results in a user-readable way, not just the raw API response. 

**Designs**
Can work on these as needed, or somebody else can hop in!

**Describe alternatives you've considered**
Not doing anything

**Additional context**
n/a

**Comment by jeffpaul** [comment]
Something like this very rough lowfi wireframe would be a nice way to preview the data that Watson returns based on the thresholds set and would allow someone to tweak those thresholds and see how it updates the data returned before fully saving those updated thresholds. (Note I would probably update the button text from "GO" to "Preview")

![image](https://user-images.githubusercontent.com/2818133/152841670-acf9199d-fe49-476f-b7df-fd7e4de2d4c3.jpeg)

**Comment by Sidsector9** [comment]
@jeffpaul regarding the 'Post Preview' box in the diagram. Does this have to function the way how the WP Customizer works? As in, show the preview using the active theme? Or can it just list out the response in a user-friendly way as Helen suggested?

One problem with the customizer-like preview is the shortage of space, especially on smaller screens to preview a post. Just wanted to know your thoughts on whether we can display a table-like structure that displays the response?

**Comment by jeffpaul** [comment]
@Sidsector9 I'd say whatever is the easiest effort is best, no need to be super precise on the view there but just enough to give someone a sense of what the content there is to validate against the resulting data from Watson.
