### ISSUE TITLE
Update image metabox copy

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#200]
**Is your enhancement related to a problem? Please describe.**

This is the current state in an image attachment page:
![Screen Shot 2020-03-06 at 3 50 17 PM](https://user-images.githubusercontent.com/2818133/76127045-4b513d00-5fc6-11ea-9dc7-d97c651e7715.png)
I would expect more users would understand "ClassifAI Image Processing" versus "Azure Computer Vision Scan" and "Rescan Alt Text" versus "Rescan Captions".  Let's update this copy accordingly.

**Describe the solution you'd like**

- [ ] update metabox title to `ClassifAI Image Processing`
- [ ] update the rescan label to `Rescan Alt Text`
- [ ] update the scan label to `Scan Alt Text`

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by sudar** [comment]
@jeffpaul 

I am interested in working on this issue.
