### ISSUE TITLE
Process existing content via Language Processing without having to update content

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#202]
**Is your enhancement related to a problem? Please describe.**
We referenced this concept in #121 but didn't get to it in v1.5 and this relates a bit to the work we're working to confirm approach on in #185, but it would be nice to have options similar to what landed in v1.5 via #135 wherein we could request content tagging via our Language Processing features without having to update an individual piece of content (which is what is currently required to trigger the language processing).

**Describe the solution you'd like**

- [ ] button on individual Post / Page screen to process content via Language Processing

**Designs**

TBD

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by thrijith** [comment]
Hi @jeffpaul - if this is available, I can take a look at this.

Query on the button:

 - Should it support Classic Editor along with Block Editor?
 - For Classic Editor should the button be placed in the publish box, or somewhere else?
 - For Block Editor, do we need a plugin sidebar for custom action buttons?

**Comment by jeffpaul** [comment]
@thrijith 

> Should it support Classic Editor along with Block Editor?

Yes.

> For Classic Editor should the button be placed in the publish box, or somewhere else?

Publish box probably makes the most sense, probably called `Generate Tags` (which admittedly isn't 100% accurate, but I cannot think of something better that doesn't include `ClassifAI` or `NLU` at this moment).

> For Block Editor, do we need a plugin sidebar for custom action buttons?

I would put a similar button in the `Status & visibility` panel.

**Comment by thrijith** [comment]
Got it, thanks for confirming!

**Comment by thrijith** [comment]
Hi @jeffpaul 

- I've started on this, for Classic editor it parses the content and generates the tags, updates the taxonomies metabox without a page reload ( hope that is the expected result )
- For Block editor, have tired updating taxonomy terms with a couple of options but doesn't seem to work.
   - If there are no direct ways to do so, will doing a page reload be okay?  

Thanks!

**Comment by jeffpaul** [comment]
@thrijith 

> If there are no direct ways to do so, will doing a page reload be okay?

Yes, as long as we ensure that any other post changes made are appropriately saved in that reload.

**Comment by dinhtungdu** [comment]
@jeffpaul After reviewing the #268, I'm a bit confused about this feature.

Asking myself when do I need this feature, I can think about only when the content is updated. But the plugin is already reprocessing the content on update.

Is there any use-case I missed?

**Comment by jeffpaul** [comment]
@dinhtungdu someone may want ClassifAI to go through and add categories/tags to older posts without having to make some minor change in those posts to have that post get sent to Watson.  I suppose that the Bulk Edit option could suffice in that case though, but I think the original thinking on this issue was to have something like the link options in the Media Library for the image processing but within posts/pages to trigger language processing.

**Comment by iamdharmesh** [comment]
@jeffpaul after merging https://github.com/10up/classifai/pull/329 we already have separate slot fill and meta box for ClassifAI. So, can we move this `Generate Tags` button under that?

**Comment by jeffpaul** [comment]
@iamdharmesh yes, though we'll want to be considerate that these are separate language and image processing functions and that we label things so they make sense if both or only one feature is enabled.

**Comment by iamdharmesh** [comment]
@jeffpaul both are related to language processing, I believe `Classify Post` is more suitable here (instead of `Generate Tags`), what do you think? 
![image](https://user-images.githubusercontent.com/10613171/188609010-0ded5ca0-d2b4-4c92-ac8a-9c4ae4a61375.png)

**Comment by jeffpaul** [comment]
@iamdharmesh agreed, go ahead and change text on the button, thanks!
