### ISSUE TITLE
Smart Cropping Existing Images in Admin

### ISSUE THREAD

**Issue by rickalee** [10up/classifai#213]
Currently users have the ability to rescan images with Describe APIs via the 'Azure Computer Vision Scan' metabox within attachments. 

Could we add an additional checkbox to 'Regenerate Thumbnails' with generateThumbnail API?

https://rickal.ee/eDu1XxeJ

**Comment by jeffpaul** [comment]
@rickalee seems reasonable, will want to make sure we've similarly tie this with #176 and related bulk edit option for `Regenerate Thumbnails` from #129.
