### ISSUE TITLE
setting IBM Watson Natural Language Understanding

### ISSUE THREAD

**Issue by marco-ita** [10up/classifai#221]
**Describe your question**

Troubles in setting up NLU: i have everything but the data i typed in keep returning an error: IBM Watson NLU Authentication Failed. Please check credentials.
Please see attached image, i am using the following values for the following fields:

API URL -> the value in "url" (see attached file)
API username -> the value in "iam_apikey_name" (see attached file)
API KEY -> the value in "apikey" (see attached file).

Am i doing anything wrong? Thanks!

<img width="500" alt="Screenshot 2020-09-05 at 10 09 57 PM" src="https://user-images.githubusercontent.com/5712024/92312800-ae974880-efc4-11ea-9d6c-449fafb02d55.png">

**Comment by jeffpaul** [comment]
@marco-ita have you followed the set up steps described here: https://github.com/10up/classifai#set-up-language-processing-via-ibm-watson?  If so, where are you running into an issue?

**Comment by jeffpaul** [comment]
@marco-ita can you confirm if you've followed our set up steps and if so where you're running into an issue?
