### ISSUE TITLE
Where the image tags are going to be attached?

### ISSUE THREAD

**Issue by marco-ita** [10up/classifai#222]
Hi guys,
i managed to activate the plugin, and i am now able to see the tags generated after i publish the post but there is something i still not see: when i upload the image, there are supposed to be image tags, but where do i find those?
Additionally, most of the times, when i click the button "generate image tag" nothing happens at all... 
Any help with it?
Am i doing anything wrong?
Thanks!

**Comment by jeffpaul** [comment]
@marco-ita when you click on an image in your media library (or click `Edit`), you'll see an `Image Tags` metabox on the right side of the WP Admin below the `Save` metabox that will contain content like what's highlighted on the ClassifAI website:
![image-tagging](https://user-images.githubusercontent.com/2818133/94200225-ade52a00-fe7f-11ea-80cc-d351cbe51bfd.png)

If you're not seeing image tags being generated, can you confirm that you've set up the Image Processing feature as described here: https://github.com/10up/classifai#set-up-image-processing-via-microsoft-azure?

**Comment by jeffpaul** [comment]
@marco-ita do you have any further questions on image tagging or can we close this issue?
