### ISSUE TITLE
Smart cropping results not as expected

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#224]
**Describe the bug**
I've tested ClassifAI 1.5.1 on WordPress 5.5.1, 5.4, and 5.3 and am seeing that image tags and alt text work as expected (yay!) but the smart cropping feature isn't providing the desired result (boo!).

**Steps to Reproduce**

1. Upload an image to the media library, example:
![dog-on-red-background](https://user-images.githubusercontent.com/2818133/94198397-d3bcff80-fe7c-11ea-95bb-d8815bd0e16a.png)
2. See that cropped thumbnail only captures the top of the dog:
![bad-crop-result](https://user-images.githubusercontent.com/2818133/94198538-0961e880-fe7d-11ea-8e69-c0cbe9c3efb6.png)
3. Click "edit" to see that alt text and image tags worked as expected.

**Expected behavior**
Resulting crop would more closely match what [Azure Computer Vision](https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/#features) demonstrates on their site:
![azure-result](https://user-images.githubusercontent.com/2818133/94198664-3f06d180-fe7d-11ea-9066-a4b3d40bb569.png)

**Screenshots**
See in-line in this issue.

**Environment information**
 - Device: Mac mini (2018)
 - OS: macOS 10.15.6
 - Browser and version: Firefox 80.0.1 (64-bit)
 - WordPress version: 5.5.1, 5.4, and 5.3 tested
 - ClassifAI 1.5.1

ClassifAI image processing settings:
![classifai-image-settings](https://user-images.githubusercontent.com/2818133/94198709-4fb74780-fe7d-11ea-9cc2-e2ddb93325db.png)

**Additional context**

I'll try and dig up the Azure API docs to see if something changed since our original implementation, but open to other triaging to help on this.

**Comment by jeffpaul** [comment]
Looks like we're referencing [v2.0](https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/56f91f2e778daf14a499e1fa) of their API: https://github.com/10up/classifai/blob/bdee8d423393123dbf6602647cd049b38cd89c0d/includes/Classifai/Providers/Azure/SmartCropping.php#L29

They've since updated to [v2.1](https://westus.dev.cognitive.microsoft.com/docs/services/5cd27ec07268f6c679a3e641/operations/56f91f2e778daf14a499f21b), [v3.0](https://westcentralus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-ga/operations/5d986960601faab4bf452005), and have a preview up for [v3.1](https://westus2.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-1-preview-2/operations/5d986960601faab4bf452005).

**Comment by jeffpaul** [comment]
Not seeing any major announcements on their blog: https://azure.microsoft.com/en-us/blog/topics/cognitive-services/

**Comment by helen** [comment]
Well that's a little annoying, maybe we should bump to 3.0 for all of the different endpoints we're using?

**Comment by jeffpaul** [comment]
@helen that's at least worth researching.  Also credit to @oscarssanchez for helping call out this issue and provide good reproduction steps.
