### ISSUE TITLE
Add automated linting for PHP and JS (CI)

### ISSUE THREAD

**Issue by helen** [10up/classifai#225]
**Is your enhancement related to a problem? Please describe.**
While there is a precommit hook, it currently only runs `phpcs` (possibly needs to be updated) and it's still possible for somebody to ignore that and push to a branch and open a PR with those errors.

**Describe the solution you'd like**
I would like to see PHPCS and ESLint running in GitHub Actions with annotations, see https://github.com/helen/wordpress-develop/pull/1/files for an example.

**Designs**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
See #209

**Comment by dinhtungdu** [comment]
Closed by #226
