### ISSUE TITLE
Do the TODOs

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#260]
**Is your enhancement related to a problem? Please describe.**
Current count of seven different [TODOs in the code](https://github.com/10up/classifai/search?q=TODO&type=code).  Let's look to work on resolving and DOing those.

**Describe the solution you'd like**
- [x] `Classifai/Providers/Azure/ComputerVision.php`: Implement reset_settings() method.
- [x] `Classifai/Providers/AWS/Comprehend.php`: Implement reset_settings() method.
- [ ] `Classifai/Providers/AWS/Comprehend.php`: Implement can_register() method.
- [x] `Classifai/Providers/AWS/Comprehend.php`: Implement sanitize_settings() method.
- [ ] `Classifai/Command/ClassifaiCommand.php`: gc
- [x] `Classifai/Providers/Provider.php`: Implement sanitize_settings() method.
- [x] `Classifai/Providers/Watson/NLU.php`: Implement can_register() method.
- [x] `Classifai/Providers/Watson/NLU.php`: Is this function, `check_license_key`, supposed to be here?
- [ ] `Classifai/Services/ServicesManager.php`: remove this requirement (see: `can_register`).

**Designs**
Probably none, but won't know until we dig into the TODOs.

**Describe alternatives you've considered**
Don't do the TODOs.  In which case, are they TODONTs?

**Additional context**
n/a

**Comment by jeffpaul** [comment]
@ActuallyConnor thanks for the PR on #264!  If you've got time there's a handful of other TODOs (see checklist noted in original description) that I'd love to get more help working through.  Either way, thanks for the help so far... cheers!

**Comment by rahulsprajapati** [comment]
> `Classifai/Providers/Provider.php`: Implement sanitize_settings() method.

Looks like this one done in: https://github.com/10up/classifai/pull/308/files#diff-39e68d5df2219939bc675114fe73e5922f0ef0ccd6c13dee7fc500ba34c8afb8

**Comment by rahulsprajapati** [comment]
Hello @jeffpaul 👋 

I have some doubt/questions about these remaining todos, can we get more details on this?

1. `Classifai/Providers/AWS/Comprehend.php`: Implement can_register() method.
    -  This AWS provider is not being used anywhere, and not sure what can_register should check for? I can see it's related to Amazon Web Services to maybe use for language or image processing but not sure what can_register should do as I don't see aws service provider option.
2. `Classifai/Command/ClassifaiCommand.php`: gc
     - Here we are running this function for each record that is being processed for classify, and this function return true for each 10th record and false for other. So maybe we are trying to clear some cache or memory after each 10 record batch is proccesed. But I'm not sure if that something we needed. 
3. `Classifai/Services/ServicesManager.php`: remove this requirement (see: can_register).
     - For this one I belive we want to remove `$service->can_register()` condition from `includes/Classifai/Plugin.php` right?
ref: https://github.com/10up/classifai/blob/cf2a6566e95160da0f9b5fc71c14731f90f9dc3b/includes/Classifai/Plugin.php#L111-L115

**Comment by jeffpaul** [comment]
1. Seems like we can probably remove the AWS provider entirely as there's nothing within ClassifAI that utilizes that service provider.  You might scan the codebase to see if there are other AWS references that we might be able to remove as well.
2. Will defer to @dkotter @dinhtungdu 
3. Will defer to @dkotter @dinhtungdu

**Comment by dkotter** [comment]
> `Classifai/Command/ClassifaiCommand.php`: gc
> - Here we are running this function for each record that is being processed for classify, and this function return true for each 10th record and false for other. So maybe we are trying to clear some cache or memory after each 10 record batch is proccesed. But I'm not sure if that something we needed.

I think this is probably correct, that this was meant to be some sort of cache clearing method. Since this isn't currently doing anything and I'm not aware of any issues around performance here, I'd suggest we just remove this method for now.

> `Classifai/Services/ServicesManager.php`: remove this requirement (see: can_register).
> - For this one I believe we want to remove `$service->can_register()` condition from `includes/Classifai/Plugin.php` right?

Looking at this one, it does appear the `can_register` method in the `ServicesManager` class isn't actually needed, though it also doesn't hurt anything to have that there. It will always return `true` and there's no way to filter or change that. We can either just remove the TODO statement from this and leave it alone or just remove this method all together and the line of code that uses this method in `includes/Classifai/Plugin.php`

**Comment by rahulsprajapati** [comment]
Thank you @jeffpaul and @dkotter for the answers and confirmation, I'll update this changes.

> Looking at this one, it does appear the can_register method in the ServicesManager class isn't actually needed, though it also doesn't hurt anything to have that there. It will always return true and there's no way to filter or change that. We can either just remove the TODO statement from this and leave it alone or just remove this method all together and the line of code that uses this method in includes/Classifai/Plugin.php

For this one, I'll go ahead and remove this method as it doesn't do anything anyway. Keeping this can cause confusion in future.
