### ISSUE TITLE
Add filter for processing on alternate post status

### ISSUE THREAD

**Issue by joedolson** [10up/classifai#266]
**Is your enhancement related to a problem? Please describe.**

We're using Watson language processing as an element in classifying whether or not a document is sufficiently topical to be published. For this to be effective, we want to run processing on posts prior to publishing them. 

**Describe the solution you'd like**

In https://github.com/10up/classifai/blob/51584310501073b7fb008139d2922e75b2fda50c/includes/Classifai/Command/ClassifaiCommand.php add a filter on post statuses to allow classification to run in contexts other than published posts. 

**Designs**

**Describe alternatives you've considered**

Alternate: Operate Watson on a private post type and switch post types if classification meets established criteria. Would prefer to us post status, however. 

**Additional context**

**Comment by jeffpaul** [comment]
We'll want to consider this alongside #185 so that they go in together sensibly and so as to not further the issue identified in 185.

**Comment by dkotter** [comment]
As mentioned on PR #330, this should be solved in #310
