### ISSUE TITLE
Post cannot be updated or saved

### ISSUE THREAD

**Issue by ajaxthemestudios** [10up/classifai#270]
**Describe the bug**

**Steps to Reproduce**

1. Upgrade Wordpress to 4.7
2. Tried to edit and update a custom post type.

**Expected behavior**
When trying to edit an existing CPT, it got stuck in an endless "updating" message. The post does not save.
When I checked the browser error, I got this - 

Uncaught (in promise) TypeError: Cannot read property '_classifai_error' of undefined
    at editor.min.js?ver=1.6.0:1
    at data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    at Array.forEach (<anonymous>)
    at i (data.min.js?ver=943087ae96d075f126df689839bb96b9:2)
    at data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    at p (data.min.js?ver=943087ae96d075f126df689839bb96b9:2)
    at redux-routine.min.js?ver=284288e957394d2097c6fbe95625e2fb:2
    at data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    at data.min.js?ver=943087ae96d075f126df689839bb96b9:2
    at dispatch (data.min.js?ver=943087ae96d075f126df689839bb96b9:2)

**Environment information**
 - Device: MSI Stealth
 - OS: Windows
 - Browser and version: Chrome Version 89.0.4389.82 (Official Build) (64-bit)
 - WordPress version: 5.7.0
 
 -There are problems with the HTTPS connection of your website

**Comment by ajaxthemestudios** [comment]
Fixed. Turned out that the support for Custom fields, page attributes, etc was disabled in the CPT

**Comment by jeffpaul** [comment]
Glad you were able to figure it out @ajaxthemestudios, let us know if you run into any other issues or have ideas on how ClassifAI can be enhanced to better meet your needs... thanks!
