### ISSUE TITLE
Arabic language support ?

### ISSUE THREAD

**Issue by Sami-AlEsh** [10up/classifai#272]
Does this plugin supports Arabic language for: Language Processing - Tagging / Image Processing - Tagging ?
I want both tags to be in Arabic ... is it possible ?

**Comment by jeffpaul** [comment]
@Sami-AlEsh as of now all content is presumed to be English.  There is an open issue (see #150) that would look to add support for multiple languages, so please follow along on that issue for updates on when that will be available.  If this is something of particularly urgent/important need for you, then please shoot me an email (jeff.paul@10up.com) and we can discuss alternate options for you... thanks!
