### ISSUE TITLE
Normalize copy around Image Processing functions

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#280]
**Is your enhancement related to a problem? Please describe.**
I received the following feedback via email:
> I believe it should be called "Use OCR to scan for text in the image" to explain what it actually does and connect back to the setting itself. The same goes for Rescan Alt Text. The setting of managing this is called "Automatically Caption Images". Not a very obvious connection. On top, you know there is actually another media meta field called Caption. To make the chance of confusion even bigger the setting is explained with "Images will be captioned with alt text upon upload". Does this mean that the Alt Text will be put as Caption as well?  It seems that the Settings dialogue and the meta box was written by two completely different departments who never spoke to each other.

**Describe the solution you'd like**
There's a solid point here where we should look at normalizing labels and helper text in different places:

**ALT TEXT**
- Setting label: `Automatically Caption Images`
- Setting helper text: `Images will be captioned with alt text upon upload`
- Threshold setting label: `Caption Confidence Threshold`
- Threshold setting helper text: `Minimum confidence score for automatically applied image captions, numeric value from 0-100. Recommended to be set to at least 75.`
- Data currently flows into the `Alternative Text` field
- Media Library image processing option label: `Scan Alt Text` and `Rescan Alt Text`

**TAGGING**
- Setting label: `Automatically Tag Images`
- Setting helper text: `Images will be tagged upon upload`
- Threshold label: `Tag Confidence Threshold`
- Threshold helper text: `Minimum confidence score for automatically applied image tags, numeric value from 0-100. Recommended to be set to at least 70.`
- Media Library image processing option label: `Generate Tags` and `Regenerate Tags`

**SMART CROPPING**
- Setting label: `Enable smart cropping`
- Setting helper text: `Crop images around a region of interest identified by ComputerVision`
- Media Library image processing option label: `Generate Smart Thumbnail` and `Regenerate Smart Thumbnail`

**OCR**
- Setting label: `Enable OCR`
- Setting helper text: `Detect text in an image and store that as post content`
- Media Library image processing option label: `Scan Text` and `Rescan Text`

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeffpaul** [comment]
Following on from this is additional feedback on the Computer Vision endpoint setting field:
> Also, in the Settings, mentioning the Endpoint URL the e.g. is "https://REGION.api.cognitive.microsoft.com/"  and that is not at all how the endpoint looks, at least not for me. Mine is "https://REDACTED.cognitiveservices.azure.com/" where the "REDACTED" was designed by my choices setting it up in Azure.

So we may want to further generalize the helper text for the `Endpoint URL` field or add a secondary example there (e.g., `https://EXAMPLE.cognitiveservices.azure.com`).

**Comment by jeffpaul** [comment]
Noting that we'll want to credit https://github.com/myBCN for the original issue report on this.

**Comment by ajmaurya99** [comment]
Hey @jeffpaul I have started a WIP PR for the above change - https://github.com/10up/classifai/pull/322
Could you please have a look, Currently I have updated all the ALT TEXT labels and helper text with the TAGGING labels and helper text.

I am not sure if the SMART CROPPING and the OCR section also requires any change.

**Comment by jeffpaul** [comment]
@ajmaurya99 #322 is an incorrect approach.  We need to work to make the copy in each section more normalized/similar so that we reference things within the Alt Text, Tagging, Smart Cropping, and OCR sections all reference terms in the same manner.  I'm going to work on getting some copyediting help on this as that will help outline the changes needed more precisely.  Until then, you can probably close that WIP PR and I'll ensure this issue is updated when we have better copy available.

**Comment by ajmaurya99** [comment]
Thanks @jeffpaul, I have closed the WIP PR.

**Comment by jeffpaul** [comment]
[Google Doc with updated copy recommendations.](https://docs.google.com/document/d/1IrUO9C7RTTn0EZiJfwlf-lu320KanxDdVKXK2DUHT-o/edit)
