### ISSUE TITLE
Fold WP-CLI docs into hookdocs site

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#281]
**Is your enhancement related to a problem? Please describe.**
In order to continue evolving our [hookdoc site](https://10up.github.io/classifai/) into a more full-featured developer documentation site, we should look to port our [WP-CLI commands docs](https://github.com/10up/classifai/#wp-cli-commands) into the hookdoc site and rename it to ClassifAI Developer Documentation ([like what ElasticPress does](https://10up.github.io/ElasticPress/)).  Similarly adding a simple reference in the README.md to our developer docs to ensure they're clearly visible and available for folks looking for that level of info.

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by ActuallyConnor** [comment]
Hey @jeffpaul I've got a PR ready for this issue. Let me know if you have any questions or want to request any changes.

[https://github.com/10up/classifai/pull/312](https://github.com/10up/classifai/pull/312)

**Comment by jeffpaul** [comment]
Awesome, many thanks @ActuallyConnor!  I've pinged our Open Source Practice team for review after making a couple minor updates and will let you know if they have any questions/concerns after review.  As always, great to see you around here and thanks again!

**Comment by ActuallyConnor** [comment]
No problem 😌

**Comment by ActuallyConnor** [comment]
@faisal-alvi @jeffpaul any possibility we could add the Hacktoberfest tag to the issue?
