### ISSUE TITLE
JavaScript error in Block Editor when ClassifAI has not been set up correctly

### ISSUE THREAD

**Issue by junaidbhura** [10up/classifai#285]
**Describe the bug**
A JavaScript error is fired in the Block Editor when ClassifAI has not been set up. This prevents a post from being saved. This occurs because ClassifAI looks for a meta value without checking for its existence.

The JavaScript error says:

> Uncaught TypeError: Cannot ready property '_classifai_error' of undefined

**Steps to Reproduce**

1. Install and activate ClassifAI
2. Do not enter any details
3. Create a post in the block editor and save, ideally one with post meta boxes
4. A JavaScript error is fired (Screenshot below)

**Expected behavior**
Post saves without any JavaScript errors.

**Screenshots**
<img width="1284" alt="Screen Shot 2021-06-04 at 7 50 03 am" src="https://user-images.githubusercontent.com/2512525/120717271-9c721880-c50a-11eb-97b7-dae06bb64365.png">

**Environment information**
 - Device: Macbook Pro
 - OS: MacOS 11.4
 - Browser and version: Brave (Chromium 91)
 - WordPress version: 5.7.2

**Additional context**

**Comment by dinhtungdu** [comment]
@junaidbhura I can't reproduce the issue on WP 5.7.2, new multisite with unconfigured ClassifAI (`develop` branch). Watching the value of `meta`, it returns an empty array in my test, which means that the variable is not undefined. Can you give me more detailed instructions?

I agree with your additional check added in #286, we should always check the existence of variable first before using them. But I want to reproduce the issue first before merging your PR.

**Comment by junaidbhura** [comment]
Hey @dinhtungdu do you think you could try it on a post type that is not configured to work with ClassifAI?

**Comment by dinhtungdu** [comment]
@junaidbhura the same thing happens for unsupported post type, they value of `meta` always is `[]`.

**Comment by junaidbhura** [comment]
Hey @dinhtungdu I've reached out to you on DM with some additional context!

**Comment by dinhtungdu** [comment]
Thanks for the clarification! I approved the PR.

**Comment by junaidbhura** [comment]
Thanks @dinhtungdu !
