### ISSUE TITLE
Trouble with Microsoft azure part

### ISSUE THREAD

**Issue by henryperkins** [10up/classifai#288]
Hello,

I'm having difficulty understanding the directions to get the needed information from Microsoft Azure Computer part.. please advise.. specifically I'm not sure what it wants in endpoint and I cannot find an API key for image processing. 

Thank you

**Describe your question**

**Comment by jeffpaul** [comment]
@PerkinCoin welcome to ClassifAI, glad to have you giving it a try!  We have instructions on [setting up Image Processing using Microsoft Azure](https://github.com/10up/classifai#set-up-image-processing-via-microsoft-azure), you should hopefully see the endpoint and API Key details as noted in step 1.  If you're not seeing those in Azure, could you please provide a screenshot of what you're seeing so we can better understand what you're seeing and try to better troubleshoot for you?
