### ISSUE TITLE
Error code: cURL error (92): Stream error in the HTTP/2 framing layer

### ISSUE THREAD

**Issue by Nikita12000** [10up/classifai#297]
**Describe your question**

Hello, 
we have installed classifai plugin in our wordpress website. Seems that something is going wrong with requests from IP xxxxx that were contested by our CAPTCHA firewall due to user agent.

Error code: cURL error (92): Stream error in the HTTP/2 framing layer

We would like to know how to solve this problem.
Thank you

**Comment by dinhtungdu** [comment]
Hi @Nikita12000, Can you provide more detailed steps to reproduce your issue? What did you do to get that error? It's easier for us to reproduce and squad this issue.
