### ISSUE TITLE
Media modal improvement for new uploads

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#304]
**Is your enhancement related to a problem? Please describe.**
Following on from #295, we'll want to investigate how to further improve the generate/regenerate/rescan buttons in the media modal when editing a post so you no longer have to click away and then back to have the buttons work.

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**
Original, larger focus issue: #292.

**Comment by dkotter** [comment]
Specific context is here: https://github.com/10up/classifai/pull/295#issuecomment-884962243
