### ISSUE TITLE
Update action-release to run as a composite step

### ISSUE THREAD

**Issue by helen** [10up/classifai#305]
**Is your enhancement related to a problem? Please describe.**
It's a Bash script so it should be able to run directly on the runner, doesn't need to spin up Docker.

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by helen** [comment]
I think we can also add the ZIP generation/attachment while we're in here.

**Comment by iamdharmesh** [comment]
> I think we can also add the ZIP generation/attachment while we're in here.

Does this mean uploading zip to release assets during the new release?

**Comment by dinhtungdu** [comment]
> Does this mean uploading zip to release assets during the new release?

@iamdharmesh yes, currently we only commit the built plugin to the `stable` branch in the release action. If we can generate a ZIP file and attach it to the release asset, it'd be awesome.

**Comment by iamdharmesh** [comment]
Okay, @dinhtungdu. Currently, the release action trigger on push to `trunk`, I will change it to `on release` and attach the zip to release assets. Thanks for the information.

**Comment by dinhtungdu** [comment]
> I will change it to on release and attach the zip to release assets

As [the release instruction](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md#release-instructions), we run the action release on the trunk to build the plugin and then push the built version to `stable`. So I don't think we can change the condition to run on releases. Instead, we can create another workflow to create and attach the zip to the release assets.

**Comment by dinhtungdu** [comment]
But looking at [the release page](https://github.com/10up/classifai/releases/tag/1.7.1), because we create releases from `stable`, the source code is already the built version of the plugin. So I don't think we need to zip and attach the built. For this issue, we only need to convert the release action to composite action. I'm sorry for the confusion @iamdharmesh!

**Comment by iamdharmesh** [comment]
Okay, @dinhtungdu. Thanks for clarifying, PR is ready for review :+1:
