### ISSUE TITLE
Split OCR processing into its own settings

### ISSUE THREAD

**Issue by helen** [10up/classifai#306]
**Is your enhancement related to a problem? Please describe.**
Technically the image one is image processing but I think since it's not enabled by default (I believe) and now has the PDF parallel which really doesn't actually belong in image processing, we should have an OCR / Text Scanning / similarly-named settings page instead.

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by dkotter** [comment]
This is now done coming out of #611, since each Feature is now it's own thing, with it's own setting page
