### ISSUE TITLE
New filter: allow content classification by $post_status

### ISSUE THREAD

**Issue by jamesmorrison** [10up/classifai#309]
**Is your enhancement related to a problem? Please describe.**
Currently, there is no hook / filter to enable content classification based on `$post_status`; content classification can only be processed where a post is actually published.

```
// Only process published, supported items and only if features are enabled
if ( 'publish' === $post_status && in_array( $post_type, $supported, true ) && \Classifai\language_processing_features_enabled() ) {
	$this->classify( $post_id );
}
```
https://github.com/10up/classifai/blob/develop/includes/Classifai/Admin/SavePostHandler.php#L66

**Describe the solution you'd like**
An additional filter; which allows an array of post statuses to be used. This will allow (for example) a post with post status `draft` to be processed (prior to publication).

**Designs**
N/A - functional changes only

**Describe alternatives you've considered**
Externally, the `Classifai\Admin\SavePostHandler` class could be extended to allow the same change.

**Comment by jeffpaul** [comment]
Tagging in @dkotter to confirm best approach on this before we get someone to work on this / align to a milestoned release.

**Comment by dkotter** [comment]
Left comments on the PR but to capture those here as well, I think we can copy how we do the supported post types, by adding a new helper method to get the supported post stati with a filter there. We could also add these as options to our settings page, which might be nice.

**Comment by jeffpaul** [comment]
@jamesmorrison @dkotter did these options get added to the settings page or should we open a subsequent issue to track that work?

**Comment by dkotter** [comment]
Yes, these got added to the settings screen
