### ISSUE TITLE
Document IBM Watson API endpoint URL update/change.

### ISSUE THREAD

**Issue by rahulsprajapati** [10up/classifai#316]
**Is your enhancement related to a problem? Please describe.**

The `watsonplatform.net` endpoint URLs were retired on 26 May 2021. ref: https://cloud.ibm.com/docs/watson?topic=watson-endpoint-change

**Describe the solution you'd like**

Add a notice about endpoint update in [readme](https://github.com/10up/classifai#set-up-language-processing-via-ibm-watson) setup section to notify users to use new api endpoints.

We can point to a link or add step on how/where to get new endpoint: https://cloud.ibm.com/docs/watson?topic=watson-endpoint-change#endpoint-find-update

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10358350/145231525-af63b0c6-f340-486d-9df8-0873abe3a339.png">

We can also add similar notice on Language Processing settings page here:

https://github.com/10up/classifai/blob/cf2a6566e95160da0f9b5fc71c14731f90f9dc3b/includes/Classifai/Providers/Watson/NLU.php#L210-L238

Note: This can be a conditional warning with comparing if API url matched `watsonplatform.net` sub/domain.

**Designs**

i.e: 
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/10358350/145233102-08996977-b63a-4686-8d36-27f3f65b1b2f.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by jeffpaul** [comment]
We should also ensure the initial state with helper text in that field notes the method IBM describes:
```api.{location}.{offering}.watson.cloud.ibm.com```

Noting that we could probably customize that further to:
```api.{location}.natural-language-understanding.watson.cloud.ibm.com```
Since we know that this part of ClassifAI uses Watson's NLU service offering.

**Comment by rahulsprajapati** [comment]
> Noting that we could probably customize that further to:
api.{location}.natural-language-understanding.watson.cloud.ibm.com
Since we know that this part of ClassifAI uses Watson's NLU service offering.

@jeffpaul about this ☝️ : 

Do you mean when user select NLU service offering they'll get url with `.natural-language-understanding.watson.cloud.ibm.com` only or you mean user can add this offering as name to `natural-language-understanding` for NLU service ?

**Comment by jeffpaul** [comment]
@rahulsprajapati I meant that assuming there's default, helper text in that field that we could list ` api.{location}.natural-language-understanding.watson.cloud.ibm.com/instances/random-string-here` as that default, helper text
