### ISSUE TITLE
Utilize the OpenAI Moderation API to filter content (comments?)

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#331]
### Enhancement idea.

OpenAI currently offers a [Moderation](https://platform.openai.com/docs/guides/moderation/overview) endpoint that is free to use. This engine allows you to pass in text and it will classify that text within a few different categories.

Thinking it would be cool to build this into Classifai as a way to determine if user generated content is safe or not. Seems most applicable for comments (think Akismet) but could also be useful on a site that accepts user content submissions, as a first line of defense.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phpbits** [comment]
+1 for using this to validate comments.

**Comment by dkotter** [comment]
Note that this feature has changed since I initially opened this issue. They've changed the naming from `Content filter` to `Moderation` and I'm a little unsure on the use cases they hope to support. In reviewing their documentation, it says:

> The moderation endpoint is free to use when monitoring the inputs and outputs of OpenAI APIs. We currently disallow other use cases

I don't know exactly how to interpret this, it almost seems like this API should only be used if you want to validate content either before sending it to another OpenAI API (like ChatGPT) or validating content received from OpenAI. In that case, sending site content (like comments) to validate may not be a use case that OpenAI supports.
