### ISSUE TITLE
Update required workflow passes to allow merge.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/classifai#353]
### Describe the bug

The settings for this repo currently require the action `phpunit` to pass to allow for merge. This is no longer reporting as the PHP Unit tests have been renamed (I think in 470489a31a03401f20606ede028f920079a604d4).

Could the required actions be updated to remove `phpunit` and add `PHPUnit Tests` in its place?

![Screen Shot 2022-07-14 at 2 28 53 pm](https://user-images.githubusercontent.com/519727/178899201-1c88db8f-f2ea-4687-9010-3a926147d8bd.png)

### Steps to Reproduce

1. Create a pull request
2. Seek and gain approval
3. Observe the merge button is disabled.

Here's one @dinhtungdu prepared earlier https://github.com/10up/classifai/pull/253

### Environment information

N/A

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dinhtungdu** [comment]
FYI, this is blocking me from merging the #253 because I don't have enough permission.

**Comment by jeffpaul** [comment]
I updated the branch protections for `develop` to remove that requirements, thanks!
