### ISSUE TITLE
Integration with Tainacan plugin

### ISSUE THREAD

**Issue by mateuswetah** [10up/classifai#360]
### Describe your question

Hi! Hope this is the place to discuss this, if not, let me now.

I am one of the developers of the [Tainacan](https://wordpress.org/plugins/tainacan/) plugin, a solution for digital archives management and exposition built on WordPress. We are a small team with a modest open source community, but with increasing number of museums and cultural archive institutions on active usage.

Recently, a user opened [an issue](https://wordpress.org/support/topic/help-accessing-images-in-media-library-via-tainacan-plug-in/) in our repository requesting, among other things, an integration with ClassifAI. She was particularly interested on having the automatic description extraction from images. As I explained there, we don't exactly use the WordPress media gallery page to source our repository items media because they are uploaded to a different folder structure, where we can keep privacy levels. But we do use a good portion of their upload and attachment flow. Actually, our media gallery modals are inherited from WordPress customize media frames, as you may have a clue [here](https://github.com/tainacan/tainacan/blob/develop/src/views/admin/js/wp-media-frames.js).

So while I understand there might be blockers to a possible integration, I also have a feeling that we might be a few steps close to it... Would you help me understand if there is a way for it? I am not aware of ClassifAI internals, but I can give details about our flow it that helps. We have previously worked on integrating our code to other plugins, such as the [ElasticPress](https://www.elasticpress.io/).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@mateuswetah I see Jeff chimed in on the .org thread but to follow up here, the user in that thread is using our OCR and automatic `alt` text features. Both of these fire on the core `wp_generate_attachment_metadata` filter. So if you're plugin makes use of that filter (which is fired by the core `wp_generate_attachment_metadata` function) things should work.

**Comment by mateuswetah** [comment]
Hey @dkotter, thank you for the reply!

In fact we could follow up that conversation and their project is running OK now. But in their case, we ended up making a migration of data as they initially uploaded data to the WordPress default gallery instead of our plugins version of it.

Would you mind keeping this issue open while we investigate during next week if we are using this filter correctly? If I understand, I should be able to simulate what you guys do by creating my own `wp_generate_attachmen_metadata` filter as I don't have a working classfAI plugin to test it.

**Comment by dkotter** [comment]
> Would you mind keeping this issue open while we investigate during next week if we are using this filter correctly

Yeah, that's totally fine.

> If I understand, I should be able to simulate what you guys do by creating my own wp_generate_attachmen_metadata filter as I don't have a working classfAI plugin to test it.

Yes, that should work. For reference, [here's](https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/Azure/ComputerVision.php#L137) where we hook into that filter ourselves and it ends up calling this [method](https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/Azure/ComputerVision.php#L599).

**Comment by mateuswetah** [comment]
Hey @dkotter, I did some tests here and in fact the usage of the filter is working and should be enough. Further integrations would require efforts from our side, such as converting your tags or image metadata to our own metadata scheme. 

Thank you for the attention and good work. I'm a fan of the [10up Gutenberg](https://gutenberg.10up.com/) documentation that you guys did BTW, its a great source for me!
