### ISSUE TITLE
[Recommended Content] Include user location data in `contextFeatures` for better personalization.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/classifai#362]
### Is your enhancement related to a problem? Please describe.

Azure Personalizer integrated in ClassifAI for "Recommended Content" block in PR https://github.com/10up/classifai/pull/343. This issue is for sending user's location data to Azure Personalizer in `contextFeatures`param of `rank` request to improve the personalization and better recommendations.

API documentation:
https://westus2.dev.cognitive.microsoft.com/docs/services/personalizer-api/operations/Rank

Some Useful links for Azure Personalizer:

[Personalizer Documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/)
[How Personalizer works](https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/how-personalizer-works)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Going to close this out as Personalizer has been deprecated by Azure
