### ISSUE TITLE
Add support for core auto-updates for registered sites

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#368]
### Is your enhancement related to a problem? Please describe.

Distributor added the ability to utilize WP core's enabling of auto-updates for plugins for registered sites (see https://github.com/10up/distributor/issues/656).  Let's similarly mimic that functionality on the plugins page in the WP Admin for registered ClassifAI sites as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TylerB24890** [comment]
Just noting this feature is implemented in https://github.com/10up/classifai/pull/400
