### ISSUE TITLE
Getting "rest_taxonomy_invalid"(404) error randomly in rest API call by editor.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/classifai#369]
### Describe the bug

Found a strange bug, Rest API calls initiated by Gutenberg to get taxonomy terms are failing with **404** (`rest_taxonomy_invalid` and `rest_no_route`) randomly. This happens randomly sometimes it happens sometimes it does not. I have attached a screenshot to give more idea of the error.

**Note:** During checking on existing issues to check if someone has faced this before, I found this [comment](https://github.com/10up/classifai/issues/335#issuecomment-1128393527) by @peterwilsoncc which mentions a similar issue.

### Steps to Reproduce

1. Setup ClassifAI and Language processing.
2. Enable all 4 taxonomy and select Watson taxonomy as taxonomy.
3. Go to the edit post page of any post.
4. Open developer tools (F12) to see network calls and console errors.
5. You will find 404 errors on API calls. (This happens randomly so, you may have to reload multiple time to get this)

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/10613171/190636820-25b99889-bbbe-41d4-83a2-c85c870c6622.png)
---
![image](https://user-images.githubusercontent.com/10613171/190636857-996c66a0-1cad-427c-8e71-e2281e25d97a.png)
---
![image](https://user-images.githubusercontent.com/10613171/190636991-9993dfba-2a83-4c7c-b7b9-6bda8a1cfd2f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ravinderk** [comment]
@iamdharmesh I am not able to reproduce issue. Can you still reproduce this issue? If yes, lets chat

**Comment by iamdharmesh** [comment]
Hey @ravinderk, Thanks for checking on this. I checked on this further and found that this is happening with my local setup using "[WP Local Docker](https://github.com/10up/wp-local-docker-v2)" only, I tried to reproduce this on Local by flywheel, but was not able to reproduce on that. Could you please try to check if you able to reproduce this on setup which uses "WP Local Docker"? 

Peter has reported something similar to this, @peterwilsoncc it was on the setup using "WP Local Docker"? Intreseted to know what causing this.

Thanks

**Comment by peterwilsoncc** [comment]
> Peter has reported something similar to this, @peterwilsoncc it was on the setup using "WP Local Docker"? Intreseted to know what causing this.

I was seeing it using a pretty standard https://github.com/chassis/chassis set up and on a public server using a pretty standard build. Unfortunately, I couldn't figure out the cause either.

**Comment by jeffpaul** [comment]
@iamdharmesh is this still occurring?

**Comment by iamdharmesh** [comment]
@jeffpaul This is not reproducing for me now.

**Comment by iamdharmesh** [comment]
Closing this. Please feel free to re-open if you are still facing this.  Thanks.
