### ISSUE TITLE
DOCS: Add snippet/tutorial to make taxanomies private on developer docs site

### ISSUE THREAD

**Issue by DenisBalan** [10up/classifai#377]
### Is your enhancement related to a problem? Please describe.

I would like to have the ability to mark taxonomies as private
`public => false`

So that i will not have indexed a lot of useless archive pages with `/?classifai-image-tags=%name%` in google.

To do that simple add an abstraction for options (like with visibility)

more info: https://www.dhirenpatel.me/disable-taxonomy-archives-wordpress/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@dkotter any preference on whether this should be enabled by default or something that would need to be filtered to change to private?

**Comment by dkotter** [comment]
I wouldn't change this to being private by default. We could definitely look to add a filter around these taxonomy arguments to make it more intuitive on how to modify those values. That said, WordPress already has their own filter that will run, so I'd almost suggest just using that.

In this particular case, you could do something like:
```php
add_filter( 'register_classifai-image-tags_taxonomy_args', function( $args ) {
	$args['public'] = false;
	return $args;
} );
```

**Comment by jeffpaul** [comment]
I'm changing this to be a documentation task to add this to our developer docs site as a snippet/tutorial on how to handle.
