### ISSUE TITLE
Multi Language in Azure

### ISSUE THREAD

**Issue by tend-ag** [10up/classifai#380]
Hi there
I wonder how to change to language from Azure's Computer Vision to get the tags in another language (e.g. German).
Is there some addition I can add to the code?
Thanks

**Comment by jeffpaul** [comment]
@raumgleiterag currently all communicating with Azure (and Watson for the language processing functionality) is handled in English only.  There is #150 that's opened to look into leveraging all other available languages for existing services, but that's not currently active on our roadmap.  If that's something you'd like to look into adding in a PR then I'd be happy to chat in more detail about potential approach there... thanks!

**Comment by tend-ag** [comment]
Hi @jeffpaul 
Thanks for the response. I twerked some code which seems to work, but that's of course not a proper way. 
So at the moment it works, but if there's some need in the future, we're happy to help
