### ISSUE TITLE
Add a "Build release zip" GitHub Action

### ISSUE THREAD

**Issue by vikrampm1** [10up/classifai#388]
### Is your enhancement related to a problem? Please describe.

A new Action is released: https://github.com/10up/action-wordpress-plugin-build-zip/. This is already set up in a few PRs: [Insert Special Characters](https://github.com/10up/insert-special-characters/pull/174), [Autoshare for Twitter](https://github.com/10up/autoshare-for-twitter/pull/201) and [Simple Podcasting](https://github.com/10up/simple-podcasting/pull/199). As an example, you can see/download the Simple Podcasting zip [here](https://github.com/10up/simple-podcasting/actions/runs/3596557206).

Please go ahead and create the same in this repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ravinderk** [comment]
@vikrampm1 is it duplicate issue: https://github.com/10up/classifai/issues/367

**Comment by vikrampm1** [comment]
@ravinderk  I think it is a duplicate, so closing this now.
