### ISSUE TITLE
Image Processing Command

### ISSUE THREAD

**Issue by jemsz** [10up/classifai#394]
### Describe your question

Hi All, noob here.
How do I execute the image processing command so that it can process all existing media? It is working properly with new uploads; however, I would like the classifai image to update the hundreds of remaining images.

Below command I currently have
wp classifai image --limit=100 --force

Thank you for the help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@jemsz as noted in the [`Image Processing Commands` section](https://10up.github.io/classifai/tutorial-wp-cli.html) of the `WP-CLI Commands` part of the ClassifAI developer docs, you can provide a comma delimited list of attachment IDs to classify:
> wp classifai image <attachment_ids> [--limit=<int>] [--skip=<skip>] [--force]
>
> <attachment_ids>: Comma delimited list of Attachment IDs to classify.

**Comment by jemsz** [comment]
Thanks @jeffpaul, I did try the above, but it doesn't seem to work. Only new images being uploaded are correctly labeled.
Below are a few examples of what I've tried.. any idea?
```
wp classifai image 30935,30936,30937 --force
wp classifai image 30935 --force
```

**Comment by av3nger** [comment]
WP-CLI won't return errors. For example, if the image cannot be publicly accessible, it will show as "processed" via CLI, but won't actually be. Given that required actions are selected via `wp-admin/admin.php?page=image_processing` and the image is accessible, I wasn't able to replicate the issue above.

**Comment by jeffpaul** [comment]
@jemsz are you using any sort of offloading plugin or process for your images or is your site behind a firewall or other security plugin?
