### ISSUE TITLE
Add Image Tags to Woocommerce Product

### ISSUE THREAD

**Issue by ghost** [10up/classifai#396]
### Describe your question

Hello, 

first of all, thanks for the awesome plugin. 
I need to use the ai generated tags of the images as product tags in woocommerce. Like how can i automatically copy the image tags (from the image that is used as featured product image) to the product tags when i create a product?

Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@berryboyz you could filter [`classifai_computer_vision_image_tags`](https://10up.github.io/classifai/classifai_computer_vision_image_tags.html) and store those as product tags.
