### ISSUE TITLE
Update all usages of `get_plugin_settings`

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#413]
### Is your enhancement related to a problem? Please describe.

This is an easy step in the direction of #404. In PR #405, I refactored the [`get_plugin_settings`](https://github.com/10up/classifai/blob/develop/includes/Classifai/Helpers.php#L30) utility function to support getting settings from a specific provider within a service. Previously this would return just the first provider within a service. I updated this utility function and used it within new code introduced in #405 but left backwards compat in place and did not update all other usages.

Ideally we would remove the backwards compat code from that function and update all current uses of that function to pass in the provider. It seemed like this was only used for the `Language Processing` service, so I think it should be as easy as updating: `get_plugin_settings( 'language_processing' )` to `get_plugin_settings( 'language_processing', 'Natural Language Understanding' )` (would need to verify that is the correct provider name).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivan-ivanic-cm** [comment]
@dkotter Added PR https://github.com/10up/classifai/pull/418
