### ISSUE TITLE
Utilize `get_asset_info` where it makes sense

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#414]
### Is your enhancement related to a problem? Please describe.

In #405 we added the [`get_asset_info`](https://github.com/10up/classifai/blob/develop/includes/Classifai/Helpers.php#L605) utility function in order to pull asset info from the generated `.asset.php` files. This was used in enqueueing of assets for ChatGPT but we should look at other places we enqueue assets and update to use this utility function where it makes sense (like in NLU).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivan-ivanic-cm** [comment]
Added PR #421
