### ISSUE TITLE
Add excerpt generation to the classic editor

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#417]
### Is your enhancement related to a problem? Please describe.

In #405 we added excerpt generation using ChatGPT, but this was only added to the excerpt section within the block editor. Opening this more as a question for now but wondering if we should look to add this same feature to the classic editor?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
If there is sufficient community request for this within the Classic Editor, then sure we can work to include that.
