### ISSUE TITLE
Add default attribution to generated images

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#429]
### Is your enhancement related to a problem? Please describe.

In #419 we added a feature where you can generate images using OpenAI and then import those into your Media Library (and insert those into your content). @jeffpaul brought up a [good point](https://github.com/10up/classifai/pull/419#issuecomment-1481249910) that we might want to add a default attribution to these images, stored in the caption field.

Right now we import these images using the `wp.mediaUtils.uploadMedia` function:
https://github.com/10up/classifai/blob/b05ed69a388e5020d99ac7748da7860bafa089c6/src/js/media-modal/views/generated-image.js#L58

As far as I can tell, this function does not allow passing in additional information to be saved (like a caption).

To accomplish this, we'll either need to fire an additional request after an image is imported to update the caption on that image or switch to importing these images by directly making requests to the media endpoint using something like `apiFetch`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derweili** [comment]
@dkotter The `uploadMedia` function actually allows passing this information directly. The `additionalData` argument can be used for this. Values passed to `additionalData` are directly forwarded to the `wp/v2/media` [REST endpoint](https://developer.wordpress.org/rest-api/reference/media/) (see [uploadMedia implementation](https://github.com/WordPress/gutenberg/blob/8227969c01680282ef232c929a03a1f0c516f2e1/packages/media-utils/src/utils/upload-media.js#L222-L226)). 
So during the upload, we can set all fields supported by the REST API, including captions.

The original comment from @jeffpaul mentioned:
> Perhaps we include a default caption of “Image generated by [OpenAI's DALL·E](https://openai.com/research/dall-e)  / [<whatever default license DALL·E applies>](https://link-to-license/)”

Is this the final naming of the caption? Where do we get the license text and license link from?

Should this text be generated dynamically (e.g. on server-side to support modifying this with filters), or should it be hardcoded in JS?

### Additional related changes
When reviewing the `uploadMedia` function and the REST API fields, I noticed, we could also set the “uploaded to” post for the attachment. We are currently not passing this information when uploading the media. So even if an image is generated for a post, it is not associated with this post, but labeled as "unattached" in the media library.

@dkotter what do you think about this. Should we add this as part of the ticket as this is also a meta information, or should we evaluate whether we want to do this on a separate ticket?

**Comment by dkotter** [comment]
> The `additionalData` argument can be used for this.

Ah, I missed this. Sounds like this will be the way to go.

> Is this the final naming of the caption? Where do we get the license text and license link from?

So in doing some light research, I'm not seeing anything about a license for the content OpenAI generates. Reading through their [Terms](https://openai.com/policies/terms-of-use), it mentions that: "OpenAI hereby assigns to you all its right, title and interest in and to Output. This means you can use Content for any purpose, including commercial purposes such as sale or publication, if you comply with these Terms".

This makes it seem as if there's no license associated with these images and you as the one generating the content has full rights. There are more details around [crediting DALL·E](https://help.openai.com/en/articles/6640875-how-should-i-credit-dall-e-in-my-work) for images that we should probably follow.

All that said, I think a default caption of "Image generated by [OpenAI's DALL·E](https://openai.com/research/dall-e)" is good enough cc/ @jeffpaul 

> Should this text be generated dynamically (e.g. on server-side to support modifying this with filters), or should it be hardcoded in JS?

I had originally just planned on hardcoding this but if it's easy enough to add this on the PHP side so it can be filtered, that would be great.

> Should we add this as part of the ticket as this is also a meta information, or should we evaluate whether we want to do this on a separate ticket

I think that would be great to add as part of the work here, thanks for catching that!
