### ISSUE TITLE
Add Checkmark box to Post/Page Admin Panel

### ISSUE THREAD

**Issue by blackghostosint** [10up/classifai#439]
### Is your enhancement related to a problem? Please describe.

I am testing this on a brand new site with 60,000 posts. I am testing a few things on this blog. I would love to see some type of notice that shows a post has been processed. SEO plugins have a keyword or link section. I would help code, but I don't really know how....

### Designs

simple works.

### Describe alternatives you've considered

none.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@blackghostosint can you share details about which ClassifAI feature you're using and how you would ideally see it enhanced with a notice per your needs?  Even hand written or simple designs in a doc are super helpful in understanding what it is you're hoping for... thanks!

**Comment by blackghostosint** [comment]
<img width="778" alt="classi" src="https://user-images.githubusercontent.com/4312279/234423951-4bad0968-9ae3-4db8-9be8-cb45fcb5e9f0.png">

Hi Jeff. The admin area of WP has the notices of things accomplished aka- links, SEO, etc. 
I think box or something added to the post area to show that something has been done would be helpful so someone doesn't do the same classifi twice for a post.
I hope the pic helps. Let me know.

**Comment by jeffpaul** [comment]
I don't think any of ClassifAI's features have that sort of information that would be worthy of further cluttering up the All Posts table list view.  Is there a specific feature or features that you think would be helpful in that space?
