### ISSUE TITLE
Ensure all required options are in new onboarding

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#449]
### Describe the bug

We added a new onboarding feature in #411. This makes it much easier to get up and running with ClassifAI. In testing that out prior to the v2.1.0 release I noticed an issue though.

Most of our existing integrations require a number of things to actually work correctly:

1. Valid credentials
2. The feature needs to be turned on
3. Other settings need to be configured typically, like which roles have access or which post statuses we should run on

The onboarding wizard properly accounts for 1 and 2 but doesn't take into account 3. I put a fix in place for both OpenAI integrations and the Azure integration prior to the v2.1.0 release (can see that change [here](https://github.com/10up/classifai/commit/9efd904ec9168e1bb596d0e146898c17c9c439bc)) but the IBM Watson integration still needs to be fixed as well as potentially re-thinking how we handle this.

The fix I put in place sets a default value to the settings we need if no values are passed when saving (which should only happen during the onboarding). While this works, it may be better to actually show those settings in the onboarding so users can tweak those to match their needs.

Here are the settings we need to account for during onboarding, in order for things to work properly (this doesn't take into account API credentials as those are already handled):

- **IBM Watson**
    - Post Statuses to Classify
    - Category, Keyword, Entity and Concept settings all need configured
- **OpenAI ChatGPT**
    - Roles - excerpt generation won't work without this set (accounted for now with defaults but we may want to adjust the defaults or bring these settings into the wizard)
- **Azure Computer Vision**
    - Tag taxonomy - image tagging doesn't work if this isn't set (accounted for now with defaults but we may want to bring this into the wizard)
- **OpenAI DALLE**
    - Roles - image generation won't work without this set (accounted for now with defaults but we may want to adjust the defaults or bring these settings into the wizard)

So right now, if you were to configure IBM Watson in the onboarding wizard, things won't actually work until you go to the main settings page and configure the things mentioned above. The other providers will work since I put in place defaults but again, we may want to bring those options into the wizard, like so:

![Screen Shot 2023-05-02 at 9 22 31 AM](https://user-images.githubusercontent.com/916738/235711339-c9543bbd-937a-4117-ab15-c64c6d711d56.png)

### Steps to Reproduce

1. Install ClassifAI on a new site and go through the onboarding wizard
2. Configure IBM Watson and don't worry about the others
3. Without going to the actual settings page, save a new post and see if any taxonomy terms are added (they shouldn't)
4. Go to the settings page for IBM Watson and configure the options that were left blank
5. Save the post again and see terms being added

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
This also gets trickier when thinking of new features that are coming, like the [OpenAI Embeddings feature](https://github.com/10up/classifai/pull/437). This requires you to choose at least one post type, one post status and one taxonomy to use. If any of those aren't chosen, things won't work. I don't know if we surface all of those options during onboarding or if we force those settings to some sort of default.

**Comment by iamdharmesh** [comment]
@dkotter @jeffpaul I tried to add the required settings for IBM Watson NLU, but it makes the onboarding form longer. We may look into applying a combination (Default values + Onboarding form) on required form settings to keep the onboarding process simple. what do you think?

Thanks. 

![screencapture-classifai-local-wp-admin-admin-php-2023-05-18-19_17_44](https://github.com/10up/classifai/assets/10613171/395e424a-57ce-4032-a65e-0621228f38be)

**Comment by dkotter** [comment]
Yeah, I don't want to overwhelm people when they are getting set up, so I don't love the idea of showing all of these options immediately.

I like the idea of ensuring we have defaults for any fields that are required for features to work. This way once something is turned on and valid authentication is in place, things work without additional configuration (this impacts NLU the most but we just merged in a bunch of new features that might also be impacted).

Beyond having proper defaults, the other option I thought of was adding secondary setting screens for each of these. So you would choose which features you want enabled, you'd then register ClassifAI and then end up on the same provider configuration screen. But after putting in valid credentials for a provider, you'd then get a new screen that has all other settings, allowing you to modify those if desired.
