### ISSUE TITLE
Fatal error on Site health screen after updating to 2.2.0

### ISSUE THREAD

**Issue by hugosolar** [10up/classifai#463]
### Describe the bug

We just noticed a fatal error on the site health screen after updating to 2.2.0 on all of our staging environments

```
 Fatal error: Uncaught Error: Classifai\Providers\Provider::get_formatted_latest_response(): Argument #1 ($data) must be of type string, array given, called in /var/www/html/wp-content/plugins/classifai/includes/Classifai/Providers/Azure/TextToSpeech.php on line 412
in /var/www/html/wp-content/plugins/classifai/includes/Classifai/Providers/Provider.php on line 404
```

### Steps to Reproduce

1.- go to Site health screen on WordPress admin
2.- check the error log or enabling a plugin like Query monitor
3.- You should see the screen stops loading 

### Screenshots, screen recording, code snippet

![Screenshot 2023-05-25 at 13 58 45](https://github.com/10up/classifai/assets/894708/8857eaf0-6d87-4e7b-a7f5-e01f82a4be3b)

### Environment information

- Server: Apache
- PHP: 8.0
- Wordpress 6.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Thanks for the report @hugosolar! I've got a [PR](https://github.com/10up/classifai/pull/466) opened up that should fix this if you have any time to help test that.
