### ISSUE TITLE
Image Generation doesn't work with Classic Editor pluign

### ISSUE THREAD

**Issue by mattbbs** [10up/classifai#465]
### Describe the bug

Not sure if this feature is eventually coming or not but currently the image generator only works with the Block Editor. We use Classic Editor and it does not work. Our workaround is to switch to block when using the generator but it would be nice to be able to use it with Classic Editor.

### Steps to Reproduce

1. Create new post in Classic Editor
2. Click on Set Featured Image - Generate Images missing
3. Switch to Block Editor, click on Set Featured Image - Generate Images is there

### Screenshots, screen recording, code snippet

![Classic Editor](https://github.com/10up/classifai/assets/134650776/989617bb-ab48-48f4-8042-7f108aed30fc)
![Block Editor](https://github.com/10up/classifai/assets/134650776/a97fe637-4746-4b4f-addf-53913ab68893)

### WordPress information

WP Current version: 6.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Thanks for the feedback @mattbbs. We have purposely not added Classic Editor support to some of our most recent features but I do think image generation is one that would be nice to support in both setups. We'll look to get this on our roadmap.
