### ISSUE TITLE
404 errors generated from Classify

### ISSUE THREAD

**Issue by PShilling** [10up/classifai#473]
Howdy,

Any advice on this one?

We have been seeing a lot or URLs like this

https://harrisonmanufacturing.com.au/?classifai-image-tags=light/feed/

... showing up in our google search console. I think because of the '/' it is generating a 404 error 

Anyone else come across this?

**Comment by dkotter** [comment]
@PShilling Thanks for the question! In looking into it, all the custom taxonomies that ClassifAI registers (`classifai-image-tags` being one of those) are set with the `rewrite` option to `false`. This means they don't have a typical archive page like the default category or tag taxonomies (and thus why that page 404s). This is done purposely as these taxonomies are meant for classification purposes as opposed to rendering on the front-end (though I do see a use-case where someone would want those archive pages to work, so maybe something for us to look to support).

As far as these showing in Google Search Console, I've not seen this before. Are these linked within your sitemaps? If so, I'd suggest seeing if there's an option to remove those from the sitemap. If you're using Yoast, there should be a place where you can mark that taxonomy as being excluded.

**Comment by PShilling** [comment]
thanks for the thoughts... Yes will check out the Yoast setup!
