### ISSUE TITLE
Integrate Azure's OpenAI offering

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#492]
### Is your enhancement related to a problem? Please describe.

ClassifAI currently has integrations with several OpenAI services, but [Azure also offers their own OpenAI wrapper service](https://learn.microsoft.com/en-ca/azure/cognitive-services/openai/overview).  We could look at updating the existing OpenAI integrations to allow Azure credentials for their wrapper alongside the existing OpenAI credentials.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
I took a look at this today and seems Azure's OpenAI integration is still not publicly available. According to their [quick start](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-studio) guide:

> Access granted to Azure OpenAI in the desired Azure subscription.
Currently, access to this service is granted only by application

I think we probably want to hold off on this integration until this is publicly available.
