### ISSUE TITLE
Add `WP-CLI` command to bulk classify items using the OpenAI Embeddings feature

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#497]
### Is your enhancement related to a problem? Please describe.

In #437 we added a feature to classify content within your existing content structure using the OpenAI Embeddings API. We should look to add a `WP-CLI` command that can be used to process items in bulk, so sites that have existing content can take advantage of this feature. We already have a `WP-CLI` command to bulk classify items using the existing NLU classification feature, so we should add a similar one for the OpenAI Embeddings feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phpbits** [comment]
@jeffpaul @dkotter Assigning this one over to me. Still in progress. Thanks!

**Comment by dkotter** [comment]
@phpbits Thanks, sounds good! If you want some examples, we recently added a `WP-CLI` command in #478 and a new PR adding a new `WP-CLI` command in #514
