### ISSUE TITLE
Onboarding and settings refactor to React

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#502]
### Is your enhancement related to a problem? Please describe.

The new user experience for onboarding and settings pages was released in [2.1.0](https://github.com/10up/classifai/releases/tag/2.1.0), but could be more easily extended as we add new service providers, new features, and even more so when we add a new service provider for an existing feature.  This tracking issue will cover the refactoring to React for the onboarding/settings experiences.  We'll also want to reduce the heavy, primary references to service providers during onboarding and more on the specific feature being enabled/configured.  We can include a note in the UI to the effect of "_Powered by <Service Provider Name>_" and only force a user to consider which service provider to select if there are multiple to choose from for a given feature.

On top of this refactoring, we'll also want to consider the following items as related requirements to this work:
- [x] #306
- [x] #449
- [ ] #50

### Designs

TBD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Nice guide that we may learn from as far as how to use the built-in WordPress React components for settings pages: https://developer.wordpress.org/news/2024/03/26/how-to-use-wordpress-react-components-for-plugin-pages/

**Comment by dkotter** [comment]
Another guide around using custom SlotFills may be helpful: https://developer.wordpress.org/news/2024/03/26/how-to-use-wordpress-react-components-for-plugin-pages/#setting-up-the-menu-and-settings-page

**Comment by jeffpaul** [comment]
Noting that as part of this, it would be good to assess the WP Core WIP Admin update Figma to see where there are missing components/etc in those designs compared to what we're planning for ClassifAI's settings refactor.
