### ISSUE TITLE
Ability to generate an image directly in the Media Library

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#503]
### Is your enhancement related to a problem? Please describe.

We've added support to generate images within the context of creating a post (for instance, generating and inserting an image into the content or as a featured image). It would be nice to have the ability to generate images outside of the content creation process, thinking maybe a new section under `Media` or a new `Generate image` button that shows on the Media Library screen (or both):

<img width="164" alt="Generate image menu item" src="https://github.com/10up/classifai/assets/916738/d37ff92f-de30-4dcc-a340-90ea0edd7158">

<img width="520" alt="Generate image button" src="https://github.com/10up/classifai/assets/916738/c39a2968-8b19-4dd9-9236-1a3fe175144b">

And clicking on either of these would take you to a custom page where you enter in a prompt, generate one or more images and then can import those images into your Media Library.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Also worth consideration here is leveraging the [Command Palette](https://github.com/WordPress/gutenberg/pull/51169) coming in WP 6.3 to allow folks to type in something like "generate image" and get to this same page as well.  It would be even cooler if they could type their prompt into the Command Palette and then have that preset in the "Generate image" screen (or perhaps jump into that flow with sending that prompt to DALLE and move straight to showing the resulting image(s)).

**Comment by phpbits** [comment]
I tried adding a `Generate Image` sub-menu opening the Media Modal automatically. @dkotter Is this the functionality you have in mind for this, or do you want a separate dashboard for this one? Thanks! cc @jeffpaul 

<img width="1925" alt="Screen Shot 2023-06-30 at 11 46 07 PM" src="https://github.com/10up/classifai/assets/3365507/5e6b5b0b-d374-419d-bb39-08f455bc38a3">

**Comment by dkotter** [comment]
@phpbits So I didn't put much thought into the actual UI though was probably thinking of a stand-alone page that we could link to. That said, this solves the same problem and provides the same UI used elsewhere, so I think I'm fine with this approach.

@jeffpaul Any thoughts on the above UI?
