### ISSUE TITLE
Incorrect example for Azure Speech Service endpoint URL

### ISSUE THREAD

**Issue by ocean90** [10up/classifai#513]
### Describe the bug

On the settings screen, the description for the endpoint URL is

> Supported protocol and hostname endpoints, e.g., https://REGION.api.cognitive.microsoft.com or https://EXAMPLE.cognitiveservices.azure.com. This can look different based on your setting choices in Azure.

And the readme says "In the Endpoint URL field, enter your API endpoint." from the "Keys and Endpoint" page.

Doing so will not show the voices dropdown because the API URL is actually `REGION.tts.speech.microsoft.com` as can be seen [here](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech?tabs=streaming#regions-and-endpoints).

### Steps to Reproduce

1. Follow the steps to set up Language Processing via Microsoft Azure
2. Note that after saving the voices dropdown is not displayed and you cannot use the text-to-speech feature.

### Screenshots, screen recording, code snippet

Setting with correct API URL:
<img width="977" alt="Bildschirmfoto 2023-06-28 um 10 44 33" src="https://github.com/10up/classifai/assets/617637/483c15b1-4fe5-4e24-9345-3da973a10bf8">

Incorrect API URL as shown in Azure:
<img width="743" alt="Bildschirmfoto 2023-06-28 um 10 45 16" src="https://github.com/10up/classifai/assets/617637/8de12a19-0b7b-4e82-bb60-4f0010eb85b2">

### WordPress information

WordPress 6.2.2 with ClassifAI 2.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Thanks for pointing this out! Fixed in #512

**Comment by ocean90** [comment]
Thanks for updating the docs!
