### ISSUE TITLE
User selected key combination are not getting preserved after saving the setting. 

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/classifai#552]
### Describe the bug

In the IBM Natural Language Understanding settings, when users select the option to add API keys using **API URL + API KEY** and save the settings, it unexpectedly displays a different combination of keys, such as **API URL + API USERNAME + API PASSWORD.** 
This discrepancy creates confusion for users, as it incorrectly appears as if they have added an API USERNAME, even though they intended to use only the API URL and API KEY.

**Expected Behavior:**
The settings should accurately reflect the user's choice and only display the selected API URL + API KEY combination, without any reference to API USERNAME.

### Steps to Reproduce

**Steps to Reproduce:**

1. Navigate to IBM Natural Language Understanding settings.
2. Choose the option to add AI keys using API URL + API KEY.
3. Save the settings.
4. Observe that the saved configuration displays API URL + API USERNAME + API PW.

### Screenshots, screen recording, code snippet

| User Selected Combination | Combination After Saving |
|--------|--------|
|![Screenshot 2023-08-02 at 5 01 03 PM](https://github.com/10up/classifai/assets/6384299/a6182621-d1d9-41c9-9587-637c68d0a9a3) | ![Screenshot 2023-08-02 at 5 01 30 PM](https://github.com/10up/classifai/assets/6384299/62e54546-cf12-4e27-bbce-1663e36b4504)|

**Detailed Explanation:**

https://github.com/10up/classifai/assets/6384299/0ad46b74-bf7d-4129-8549-f3fc383d7664

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
**Update:**

With https://github.com/10up/classifai/pull/771, we have moved to the new React-based settings, and this issue no longer exists there. @ankitguptaindia, could you please help review the new settings in the context of this issue?
