### ISSUE TITLE
Add Composer type attribute

### ISSUE THREAD

**Issue by christianc1** [10up/classifai#56]
To ease installation via Composer, suggesting we add the following to the `composer.json`.
```js
{
  "type": "wordpress-plugin"
}
```

**Comment by jeffpaul** [comment]
@christianc1 seems reasonable, want to fire off a quick PR to cover that?

**Comment by christianc1** [comment]
Done @jeffpaul .  Also added `license` attribute so `composer validate` won't throw any errors/warnings.

**Comment by jeffpaul** [comment]
@christianc1 awesome, many thanks!  I'll let this sit until @helen can give the `composer.json` file another review to see if anything else should be added alongside your additions.  Thanks again!

**Comment by helen** [comment]
Fixed in #57
