### ISSUE TITLE
Prompt and payload filter standardization

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#586]
### Is your enhancement related to a problem? Please describe.

The focus here is on ensuring that filters exist for the prompts and/or payloads of all features, are standardized to a reliable format (e.g., classifai_{feature}_{service}_prompt), and that any pre-existing filters that need to be standardized are updated/deprecated accordingly (e.g. soft deprecation in one major release, hard deprecated in a subsequent major release).  This will allow for reliable filters regardless of feature and service provider and that [ClassifAI’s Developer Documentation](https://10up.github.io/classifai/) becomes easier to read and understand.

The potential approach to working on this could be:
* Go through the plugin and make a note of all hooks (probably pull these into a Google Sheet)
* During this process, make a note of any places that are missing hooks that would benefit from having one added
* Once done, we can have a conversation on which hooks we should add and which of the existing hooks should be renamed
* After all this, the actual work can be done

### Designs

n/a

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
Update: We are working on a sheet that lists all existing filters and what modifications need to be made. The sheet is available [here](https://docs.google.com/spreadsheets/d/161rtMEHuRc4VDdpS6g-dHofFBiXSB84LO1HNkRxB8d0/edit?usp=sharing).
