### ISSUE TITLE
Controlling feature availability

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#589]
### Is your enhancement related to a problem? Please describe.

Most features have the ability to enable/disable them directly within their Setup/Settings pages on a binary sitewide basis, but in cases where specific features do not have a toggle one will be added to ensure that you can enable/disable each individual feature on each site via the admin UI.  We should also ensure that all features can be enabled/disabled via hooks so that you could have an MU plugin that sets site-wide defaults for feature availability.

From a high-level estimation perspective, this will likely be a rather straightforward effort (“t-shirt sized” S) and feasibly completed within 1-3 days.

### Designs

n/a

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ravinderk** [comment]
> We should also ensure that all features can be enabled/disabled via hooks so that you can have an MU plugin that sets site-wide defaults for feature availability.

@jeffpaul In this case, we should display a message (non-dismissable) to an admin about settings that can not be changed on setting pages. What do you think?

cc: @dkotter

**Comment by ravinderk** [comment]
> Most features have the ability to enable/disable them directly within their Setup/Settings pages on a binary sitewide basis, but in cases where specific features do not have a toggle, one will be added to ensure that you can enable/disable each individual feature on each site via the admin UI

@dkotter I visited the ClassIfAI plugin settings, and In my opinion, we have settings for most features. I did not see the requirement of adding a toggle setting for AI features. I will continue to work on implementing filter hooks to toggle settings programmatically.

Let me know if I miss anything.

**Comment by jeffpaul** [comment]
> @jeffpaul In this case, we should display a message (non-dismissable) to an admin about settings that can not be changed on setting pages. What do you think?

Let's not worry about that.  If someone creates an MU plugin that blocks certain things, then that could include an admin notice if useful for their site.

> @jeffpaul In this case, we should display a message (non-dismissable) to an admin about settings that can not be changed on setting pages. What do you think?

I'm not seeing an enable/disable toggle for:
- Language Processing / IBM Watson / Natural Language Understanding
- Language Processing / Microsoft Azure / Text to Speech
- Recommended Content / Microsoft Azure / AI Personalizer

**Comment by iamdharmesh** [comment]
@jeffpaul we can close this as this is already implemented and merged in #614 

cc: @dkotter
