### ISSUE TITLE
recommended content integration updates?

### ISSUE THREAD

**Issue by Frankie-Rivers** [10up/classifai#593]
### Describe your question

can't create AI personalizer resource on MS Azure they removed the creation for this feature for recommended content integration on ClassifAI any future updates on changes or alternate solutions for this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Thanks for the question @Frankie-Rivers. We were notified on this ourselves and are currently in the process doing some research on other services we could utilize for recommended content. Follow #392 for updates on that.
