### ISSUE TITLE
Add built version for GH-powered updates

### ISSUE THREAD

**Issue by helen** [10up/classifai#61]
Right now you have to build the plugin to fully run it - we need to have a built version available as well as the current plan is to have the plugin update via GitHub. We can do this similarly to Distributor, where we build into a `stable` branch which is what gets tagged, and the merge commits to `master` represent the dev parallel (we can also tag dev versions if we really need to). I will take a quick look to see if an in-repo GH Action is relatively simple to implement and then go from there.

**Comment by jeffpaul** [comment]
If a GH Action won't work, then we've got [Release Instructions](https://github.com/10up/classifai/blob/develop/CONTRIBUTING.md#release-instructions) described that we can try to utilize like Distributor.
