### ISSUE TITLE
Content Classifcation within existing Taxonomy is not properly working. Creating new categories automatically which is not required

### ISSUE THREAD

**Issue by aniinda** [10up/classifai#615]
I have recently started using the Classifai Plugin and has set up the same on our wordpress, the content is by far impressive execept the fact that content is going beyond set instructions. Our wordpress already has existing category taxonomy present as per IAB Category taxonomy, but the plugin on processing of the content is automatically creating new category and disregarding the existing category which is a match already.. how to resolve this?

**Comment by dkotter** [comment]
@aclrys Thanks for the report! Two questions up front:

1. Are you using the OpenAI Embeddings feature for this classification? Or the IBM Watson feature? Note that classification within your existing taxonomies only works for OpenAI, not IBM Watson
2. You mention `IAB Category taxonomy`. I'm not familiar with this, is that a plugin or something else?

**Comment by aniinda** [comment]
Hi Darin,

Thanks for replying back on the following issue,
I have been extensively testing the Classif AI plugin on our wordpress instance, By far the capabilities and concepts are looking wonderful but some hinges are always coming in some areas which I want to understand from you in case I am able to properly understand and interpreting the same or is there anything I am missing out.

If you check my below screenshot, you will notice that I have activated the Image Processing using Microsoft’s AI Vision, however its not working because I don’t see any images being properly analysed and Alt-text, Image caption and other details are being generated.

Even when I am trying to add the images into post for the 1st time while writing a new post, I don’t see that its getting added too.

Do you have any manual, or get started guide with this plugin which I can use or check?

Aninda

**Comment by jeffpaul** [comment]
@aclrys your screenshot did not come through in your email response.  Could you please log into the GitHub issue to attach it so we can better help triage this for you?

**Comment by dkotter** [comment]
@aclrys For the Azure AI Vision processing, see these details on how to get that working: https://github.com/10up/classifai#set-up-image-processing-via-microsoft-azure
