### ISSUE TITLE
'Classify Content' Setting Checkbox Behavior Changes

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/classifai#643]
### Is your enhancement related to a problem? Please describe.

The current behavior of the 'Classify Content' setting is to enable/disable all settings related to IBM Watson NLU features. Upon further investigation, I observed that when this checkbox is disabled, the settings below it remain visible but non-functional. To enhance user experience, it would be more intuitive to dynamically hide/show the settings below based on the state of the checkbox.

**Proposed Changes:**

- When the 'Classify Content' checkbox is disabled, hide all settings below it.
- When the checkbox is enabled, reveal and enable the settings for user interaction. 

![Screenshot 2023-12-20 at 3 00 15 PM](https://github.com/10up/classifai/assets/6384299/3b9a7da7-8495-4819-bd92-9fd26e575b25)

**Benefits:**

- Improved User Experience: Dynamically adjusting the visibility of settings based on the checkbox state ensures that users see only relevant options.

- Clarity in Configuration: Users will have a clear visual indication of which settings are applicable, reducing confusion and potential misconfigurations.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
With the updated settings UI in https://github.com/10up/classifai/pull/824, users can visit the settings for enabled features only, which resolves this issue. Linking this issue to the PR so it will be closed upon the PR's merge.
