### ISSUE TITLE
Preserve Taxonomy Settings When Enabling/Disabling 'Classify Content' Setting

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/classifai#644]
### Describe the bug

There is an issue where, upon disabling the 'Classify Content' setting, the taxonomy dropdown options are reset to default when the setting is re-enabled. This behaviour results in an undesired complexity for users who have previously configured specific taxonomy settings.

**Expected Behavior:**

Taxonomy settings should be preserved when the 'Classify Content' setting is disabled and re-enabled. Users should not experience a reset to default options in the taxonomy dropdown.

**Impact:**

This issue may cause inconvenience for users who rely on specific taxonomy configurations, as they need to reconfigure settings every time the 'Classify Content' setting is toggled.

### Steps to Reproduce

1. Save taxonomy settings while 'Classify Content' is enabled.
2. Disable the 'Classify Content' setting.
3. Re-enable the 'Classify Content' setting.
4. Observe that the taxonomy dropdown options have reset to default.

### Screenshots, screen recording, code snippet

**Watch this video for more details**

https://github.com/10up/classifai/assets/6384299/a895bc42-cced-41f6-b66d-7471b21df5e5

### Environment information

- WordPress: 6.4.2
- PHP: 8.0.30
- Server: nginx/1.16.0
- Database: mysqli (Server: 5.7.28 / Client: mysqlnd 8.0.30)
- Browser: Chrome 120.0.0.0
- OS: macOS
- Theme: Twenty Fifteen 3.6
- Plugins:
  * ClassifAI 2.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
@ankitguptaindia This issue is fixed in the new React-based settings. could you please help to validate this on your end?

Thank you.
