### ISSUE TITLE
Super Admin access to the plugin's features

### ISSUE THREAD

**Issue by gsarig** [10up/classifai#658]
### Is your enhancement related to a problem? Please describe.

When on a multisite setup, the Super Admin role isn't listed among the Allowed Roles. Therefore,  Super Admins cannot access the plugin's features unless they make themselves Administrators to the specific site. I would expect that a Super Admin would have access to any feature that a site Administrator has, even if they are not explicitly set as users on a specific site. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@dkotter my initial reaction here is super admins should be able to access the settings page for any site on the network and where admins are granted access to enabled features then also having access there on specific sites.  Thoughts?

**Comment by dkotter** [comment]
> @dkotter my initial reaction here is super admins should be able to access the settings page for any site on the network and where admins are granted access to enabled features then also having access there on specific sites. Thoughts?

Yeah, I think that's a good middle ground. I know often the approach is to just give super admins access to everything (so in this case, they'd have access to all features without having to select a role) but I think equating admins and super admins in this case makes sense.

**Comment by MadtownLems** [comment]
I just ran into this. I'm a Super Admin on our network, and while I could manage the settings for the plugin, I could not actually use the tools (such as generate title) until I added myself as an administrator.
