### ISSUE TITLE
Removing HTML superscript and subscript tags with its contents for text to speech

### ISSUE THREAD

**Issue by Sidsector9** [10up/classifai#659]
### Is your enhancement related to a problem? Please describe.

<img width="656" alt="Screenshot 2024-01-14 at 1 59 31 PM" src="https://github.com/10up/classifai/assets/17757960/0eea431d-3330-4958-9b15-0b0db327adb9">

When the post content has `<sup>` and `<sub>` tags, the tags are stripped but the content, in this case the number `3` is left out. When the text to speech transform is done, it reads **Ancient Egyptians three**, which changes the meaning of the sentence.

This is an opinionated enhancement request and I think it'll be good to strip the content along with these tags. Or at least we can provide a setting to toggle this behaviour. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CacheMeOwside** [comment]
Hi @Sidsector9, I would like to work on this issue.

**Comment by Sidsector9** [comment]
Hi @CacheMeOwside welcome to ClassifAI! I've assigned you the issue.
