### ISSUE TITLE
Add dev version banner

### ISSUE THREAD

**Issue by helen** [10up/classifai#66]
ClassifAI is not actually runnable out of `develop`/`master`, so we should show a banner warning that you need to run `npm install && npm run build && composer install` for full functionality (if it doesn't straight up fatal without the vendor library, if it does we need to handle that more gracefully as well). We can take cues from Distributor for this, if using the `-dev` version suffix will need to update the build workflow to handle that as well.

**Comment by jeffpaul** [comment]
Adding in context from I received in one of my email conversations with someone who's tested ClassifAI.
> As far as the installation documentation, I can offer the following insights, which I did not find anywhere
> 
> Prerequisites:
> - node installed
> - php & php-composer installed
> 
> Installation:
> - clone to your blog plugin directory
`	git clone --single-branch —branch master https://github.com/10up/classifai.git /my-blog/wp-content/plugins/`
> - php build
`	cd /my-blog/wp-content/plugins/classifai && composer install`
> - node build
`	cd /my-blog/wp-content/plugins/classifai && npm install && npm run build`

**Comment by helen** [comment]
Okay so this fatals without the vendor directory, I think what we can do for now is detect that and then add the proper `-dev` version suffix stuff with a broader build process overhaul in 1.5.
