### ISSUE TITLE
Existing default prompts are not getting changed with added custom prompt

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#660]
### Describe the bug

Title generation > Custom prompt >  Enter title and prompt > Click on set as default prompt> Existing default prompts are not getting changed with custom prompt

### Steps to Reproduce

1. Go to title generation > Custom prompt 
2.  Enter title and prompt > Click on set as default prompt
3.  Existing default prompts are not getting changed with custom prompt

### Screenshots, screen recording, code snippet

https://prnt.sc/1R7xQvgiZ9Y4

### Environment information

Local

### WordPress information

WordPress version 6.4.2 , PHP version 8.1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
I believe this is working now with the latest changes in #611
