### ISSUE TITLE
I am getting an undefined text message for seconds, and then the preview result is showing.

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#663]
### Describe the bug

BE > Preview Language Processing > If you click on the Preview button, then for a second you got an undefined text message, and then the preview result is showing.

### Steps to Reproduce

1. Go to BE > Tools > ClassifAI
2. Go to Language Processing classification 
3. Click on the Preview button 
4. Observe

### Screenshots, screen recording, code snippet

https://prnt.sc/eN-53eXa6CsK

Expected Result: loader should be shown instead of undefined text

### Environment information

Local

### WordPress information

Wordpress 6.4.2 , PHP 8.1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Probably worth including a more useful "Identifying recommended classifications..." sort of loading message there instead?
