### ISSUE TITLE
FE (Safari browser) > Listen to this post button icon, which is not shown properly.

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#666]
### Describe the bug

FE (Safari browser) > Listen to this post button icon, which is not shown properly.

### Steps to Reproduce

1. Go to post which contain text to speech 
2. Open this post on Safari browser
3. Check Listen to this post button icon

### Screenshots, screen recording, code snippet

BE SS: https://prnt.sc/oJHLZk_0gFMu
FE SS: https://prnt.sc/vg_nzPh64Z5b

Expected result SS: https://prnt.sc/mMFfm2gofx0d

### Environment information

Local

### WordPress information

Wordpress 6.4.2 , PHP 8.1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@QAharshalkadu does clicking the circle icon on Safari play the audio?

**Comment by QAharshalkadu** [comment]
@jeffpaul  Yes, clicking on the circle works.
