### ISSUE TITLE
Re-enable `trunk` E2E tests

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#668]
### Is your enhancement related to a problem? Please describe.

Coming out of #611, there were some failing E2E tests on `trunk` only. In looking at most of those, they were issues with the `openDocumentSettingsSidebar` command that comes from our [Cypress WP Utils library](https://github.com/10up/cypress-wp-utils/blob/develop/src/commands/open-document-settings-sidebar.ts). My assumption is something has changed within the Block Editor and that command needs updated to account for that change.

Since this is an upstream fix, I disabled the running of E2E tests on `trunk` for now. As soon as that upstream change is made though, we should open a PR to pull in those changes and re-enable the tests, fixing any other issues that we may find at that point.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Note that I'm moving this out of the v3 milestone assuming that if WP 6.4 and 6.2 (ClassifAI's current max and min WP versions) are passing for e2e tests, then that's the important bits for a v3 release.  WP 6.5 isn't due out for almost 2 months, so we've got a bit more time to sort out why WP trunk is failing on e2e tests and get that fixed but I don't think we need to block the v3 release in resolving that.

**Comment by dkotter** [comment]
This is done in https://github.com/10up/classifai/commit/04deade2a7219037b9a6fc660e7eb1c413ae180d so closing this out
