### ISSUE TITLE
Bring more parity between the Watson NLU and OpenAI Embeddings classification providers

### ISSUE THREAD

**Issue by dkotter** [10up/classifai#671]
### Is your enhancement related to a problem? Please describe.

In the refactoring done in #611, we merged the Watson NLU and OpenAI Embeddings features into a single Feature, where you can now choose the Provider you want to use.

This all seems to be working but most of the functionality for this Feature exists within each individual Provider. Ideally that functionality should be moved into the Feature and as part of that process, ensure that things function mostly the same irregardless of which Provider is selected.

For instance, if you choose Watson as the Provider, there's a fairly new Manual Review mode. But this isn't something that is available if OpenAI is chosen.

Ultimately there are differences in how these two Providers work but we should work to bring these as close to parity as possible and in that process, move most of the code from the individual Providers into the Feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@dkotter I thought there was a specific issue about having the OAI-powered classification feature allow for recommending terms that don't exist on a site.  I can see where OAI Embeddings won't be able to do that, but perhaps that's where ChatCPT could come into play and allow for sending a post to that and ask for recommendations?

**Comment by dkotter** [comment]
> I thought there was a specific issue about having the OAI-powered classification feature allow for recommending terms that don't exist on a site. I can see where OAI Embeddings won't be able to do that, but perhaps that's where ChatCPT could come into play and allow for sending a post to that and ask for recommendations?

I don't recall there being an issue for tracking this and can't find one doing a quick search. That said, this could definitely work, where we send the content to ChatCPT and have them evaluate it and send back suggested terms. We'd have to figure out how to get that to work in our existing structure, since right now it expects the results to come with a score and that's not something we'd get using ChatCPT (though I guess even there we could ask it to return a relevancy score and see how that works)
