### ISSUE TITLE
Image Processing: No user friendly notice displayed when error occurs

### ISSUE THREAD

**Issue by faisal-alvi** [10up/classifai#686]
### Describe the bug

While on the image editing screen, I attempted to generate the image title, but the spinner continued spinning, and no error message/information was displayed. Upon inspecting the console, I encountered a message indicating that I had exceeded the API quota. It is essential to have a user-friendly notification visibly present on the page to inform users about the actual cause. Also, the spinner should be stopped, and the "Generate titles" button should be displayed again.

### Steps to Reproduce

1. Upload new image in media
2. Edit the image
3. Click the "Generate titles" button

### Screenshots, screen recording, code snippet

![image](https://github.com/10up/classifai/assets/25176325/fb84d894-a8a6-418b-8b4f-f56f066d6757)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Tested this out myself and can reproduce but does seem to only impact content using the Classic Editor. Verified that in the Block Editor, we do output an error message if needed.

I didn't test but I think this would also impact the generation of excerpts in the Classic Editor. Code for both of those lives here: https://github.com/10up/classifai/tree/develop/src/js/openai. We'll need to add error handling after we make the API request.

Might also be worth discussing on what post types we want to show these buttons. In this example, the Generate Titles button is showing when editing a media item, which probably doesn't make sense to have as there's usually not much text content associated with a media item to generate a title in the first place (or an excerpt). Doesn't hurt to have those options there but we may want to remove them.
