### ISSUE TITLE
Moderation > Getting a fatal error on the edit screen of users comments on posts

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#699]
### Describe the bug

Moderation > Getting a fatal error on the edit screen of users comments on posts

### Steps to Reproduce

1. Enabled Moderation feature of ClassifAI plugin
2. Add/edit the post > Enable post comments
3. Add few comment on post > click on edit button from comment
4. On edit comment page getting fatal error. 

### Screenshots, screen recording, code snippet

SS:
<img width="1671" alt="image" src="https://github.com/10up/classifai/assets/137804688/e6622717-cc38-4c57-8f41-871186fe325e">

<img width="1668" alt="image" src="https://github.com/10up/classifai/assets/137804688/222ee40d-3eea-49ee-b095-db220b53a634">

### Environment information

Local

### WordPress information

Wordpress 6.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qasumitbagthariya** [comment]
@QAharshalkadu I can reproduce the same issue while editing the screen of the user's comments.

![image](https://github.com/10up/classifai/assets/67687255/f8384131-c985-484d-891c-56d5594f605a)


```
[08-Feb-2024 12:51:00 UTC] PHP Fatal error:  Uncaught TypeError: Classifai\Providers\Watson\NLU::add_classifai_meta_box(): Argument #2 ($post) must be of type WP_Post, WP_Comment given, called in /Users/sumitbagthariya/Local Sites/osp/app/public/wp-includes/class-wp-hook.php on line 324 and defined in /Users/sumitbagthariya/Local Sites/osp/app/public/wp-content/plugins/classifai-1/includes/Classifai/Providers/Watson/NLU.php:657
Stack trace:
#0 /Users/sumitbagthariya/Local Sites/osp/app/public/wp-includes/class-wp-hook.php(324): Classifai\Providers\Watson\NLU->add_classifai_meta_box('comment', Object(WP_Comment))
#1 /Users/sumitbagthariya/Local Sites/osp/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /Users/sumitbagthariya/Local Sites/osp/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /Users/sumitbagthariya/Local Sites/osp/app/public/wp-admin/edit-form-comment.php(257): do_action('add_meta_boxes', 'comment', Object(WP_Comment))
#4 /Users/sumitbagthariya/Local Sites/osp/app/public/wp-admin/comment.php(92): require('/Users/sumitbag...')
#5 {main}
  thrown in /Users/sumitbagthariya/Local Sites/osp/app/public/wp-content/plugins/classifai-1/includes/Classifai/Providers/Watson/NLU.php on line 657

```

**Comment by dkotter** [comment]
I'm currently working on a PR to address #671 which will also fix this issue (as this issue is related to the Classification Feature and not the Moderation Feature).
