### ISSUE TITLE
Image generation > Link getting expired

### ISSUE THREAD

**Issue by qasumitbagthariya** [10up/classifai#703]
### Describe the bug

When we click on Generate image it looks like the URL is expired.

### Steps to Reproduce

1. Go to Media > Library
2. Switch mode to list view
1. Goto Media > Generate Image
2. Click on Generate Image
3. See error

### Screenshots, screen recording, code snippet

https://github.com/10up/classifai/assets/67687255/5f418dca-47cf-4a8a-a606-dbb9451ebbf6

### Environment information

- WordPress: 6.4.3
- Theme: Twenty TwentyVersion: 2.5
- WooCommerce - 8.5.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome
- OS: macOS Ventura 13.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sidsector9** [comment]
@qasumitbagthariya I'm unable to reproduce this issue. Please watch the following video:


https://github.com/10up/classifai/assets/17757960/11e0bb06-c08e-48b7-bf7f-c233cf4d11ec

**Comment by qasumitbagthariya** [comment]
@Sidsector9 The issue happens only in media > list mode. I have update the Steps to Reproduce. Can you please check again from your end.
