### ISSUE TITLE
Image processing > Descriptive text generator > Upload image > Labels and buttons are not aligned in line.

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#704]
### Describe the bug

Image processing > Descriptive text generator > Upload image > Labels and buttons are not aligned in line.

The labels ie. Descriptive text, Image tags, smart thumbnail,s and buttons generate, and regenerate should be aligned in line

### Steps to Reproduce

1 Add/edit post 
2. add image block
3. upload image > select image 
4. RHS > Attachments details section scroll to the bottom
5. Check fields label and buttons

### Screenshots, screen recording, code snippet

https://prnt.sc/DOky_Walf3lv
https://prnt.sc/YSuKQP5qnm75

### Environment information

Local

### WordPress information

WordPress 6.4.3 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamespstyles** [comment]
I'll try take a look at this one @jeffpaul

**Comment by jamespstyles** [comment]
@QAharshalkadu @jeffpaul @dkotter, I'm not sure if we will want to make adjustments here. I believe the fields are rendering correctly. At wider screen widths the buttons all align.

![wider width](https://github.com/user-attachments/assets/9233779c-1d81-4e69-a42d-6d55286a6bc7)


On narrower widths the longer labels "_Descriptive text_" and "_Smart thumbnail_" cause the buttons to wrap underneath. This is consistent with the regular fields: note the alignment on the "_Alternative Text_" textarea input shown below.

![narrower with wrapping](https://github.com/user-attachments/assets/1d442941-7f24-4942-8f5b-cc475be067e8)


However perhaps consistency with the regular fields isn't essential and adding some custom css to improve/tidy up these fields and to make them visually different may even be desirable. For example currently it not necessarily apparent that these fields are associated with Classifai's functionality - just a thought.

**Comment by dkotter** [comment]
Thanks for looking into this! I personally think that what we have is fine and works as well as it can within the current UI. I'd suggest we just close this out
