### ISSUE TITLE
Image processing > Descriptive text generator > Upload media and select image > For Descriptive text, Image tags, Smart thumbnail getting Error: Image URL is not accessible. 

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#705]
### Describe the bug

Image processing > Descriptive text generator > Upload media and select image > For Descriptive text, Image tags, Smart thumbnail getting Error: Image URL is not accessible. 

### Steps to Reproduce

1 Add/edit post
2. Add image block
3. upload media > select image
4. RHS > Attachments details section scroll to the bottom
5. For the field Descriptive text click on the button to generate
6.  For the field Image tags click on the button to generate
7.  For the field Descriptive text click on the button regenerate
8. Observe

### Screenshots, screen recording, code snippet

<img width="1516" alt="image" src="https://github.com/10up/classifai/assets/137804688/7d49c3fe-987b-4ddd-9a75-b3aea1e84404">

### Environment information

local

### WordPress information

WordPress 6.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @QAharshalkadu, 

Thank you for reporting the issue. It appears that you are testing these features on a local site. Consequently, Vision services are unable to access the image from the URL. Could you please try again after making your site publicly accessible? You can use `ngrok` or perhaps an Instawp instance will be fine here.

Thanks.

**Comment by QAharshalkadu** [comment]
Hi @iamdharmesh ,

I tested this issue in other QA environments but couldn't reproduce it there.
So, Closing.
