### ISSUE TITLE
Conditional Display of Helper Text for AI Provider Account Creation

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/classifai#715]
### Describe the bug

**Description:** 
The helper text, such as 'Don't have an IBM Cloud account yet? Register for one and set up a Natural Language Understanding Resource to get your API key.', should be displayed conditionally. It should only appear when the credentials fields are empty or contain incorrect credentials. 

**Use Case:**
When the service is successfully configured, it implies that the admin already has an account, allowing them to set up the service correctly. Therefore, if the admin has already configured an account, this helper text is not useful on the screen. 

### Steps to Reproduce

**Steps:**

1. Begin setting up the plugin.
2. Enter the correct credentials for the AI provider.
3. Save the settings.

Branch- `develop`

### Screenshots, screen recording, code snippet

When fields are empty - this text will help the user to create an account and setup a plugin.

![image](https://github.com/10up/classifai/assets/6384299/17fc5a5f-24e9-4c2d-b92c-fece3016629f)

When Setting is configured successfully, this can be hidden:

![image](https://github.com/10up/classifai/assets/6384299/ab08ab85-6c75-4cc8-b330-b6eef7d791df)

Example - 

![image](https://github.com/10up/classifai/assets/6384299/3b97da47-0b79-46ca-860f-452fae20b49d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kmgalanakis** [comment]
Hello @ankitguptaindia (cc @jeffpaul). I'm assuming that we need the helper texts to be removed from all the services when they are properly configured, right?

**Comment by ankitguptaindia** [comment]
@kmgalanakis Yes, that's correct. When a service is properly configured, it signifies that the user has successfully set up. To enhance user experience and streamline interface clarity, we can implement a conditional approach to display helper texts only when a service is not yet configured.
