### ISSUE TITLE
Fatal error: Missing format specifier at end of string in `classifai.php:91`

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/classifai#743]
### Describe the bug

See in PHP 8.0.30

The `sprintf` function call doesn't include a format specifier for the string to be replaced. Instead of `%s` it's `%`.

https://github.com/10up/classifai/blob/fd8991c78b9ac4761a4740bbb974ccc0157d1ca4/classifai.php#L91

Running PHP 8.0 (and possibly other versions) this causes a fatal error during activation of the plugin.

### Steps to Reproduce

1. Configure classifai on a PHP 8.0 server
2. Run `npm i; composer i; npm run build` in the command line
3. Attempt to activate the plugin
4. Activation will fail due to a fatal error

### Screenshots, screen recording, code snippet

```
[07-Mar-2024 00:10:18 UTC] PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /vagrant/content/plugins/classifai/classifai.php:91
Stack trace:
#0 /vagrant/content/plugins/classifai/classifai.php(91): sprintf('Fatal Error: Co...', '/vagrant/conten...')
#1 /vagrant/content/plugins/classifai/classifai.php(116): classifai_autoload()
#2 /vagrant/content/plugins/classifai/classifai.php(152): classifai_autorun()
#3 /vagrant/wp-build/wp-admin/includes/plugin.php(2389): include_once('/vagrant/conten...')
#4 /vagrant/wp-build/wp-admin/includes/plugin.php(675): plugin_sandbox_scrape('classifai/class...')
#5 /vagrant/wp-build/wp-admin/plugins.php(60): activate_plugin('classifai/class...', 'http://xu-class...', false)
#6 {main}
  thrown in /vagrant/content/plugins/classifai/classifai.php on line 91
```

### Environment information

- PHP 8.0.30
- WordPress trunk @ 4d6941a48b230e0a40409f5732ab3dac1facb052 in the [wordpress/wordpress](https://github.com/wordpress/wordpress) repo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
I believe #740 fixes this

**Comment by peterwilsoncc** [comment]
Sorry Darin, I'm still on my first tab for the reviews you sent through.
