### ISSUE TITLE
Expand upon Azure Computer Vision for image classification

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#75]
**Is your enhancement related to a problem? Please describe.**
Expand upon the initial work done in #51 and add additional features from Computer Vision.

**Describe the solution you'd like**
- [x] Automated tagging
- [x] All automated tasks available to turn on/off via Settings
- [x] UI to add tags alongside automated ones
- [x] ability to remove automated tags

**Out of scope features**
~- [ ] hook to catch the alt text being sent back from the Azure API (in case these need to be presented/filtered by specific consumer integrations)~ {moved to #138}
~- [ ] UI for filtering in the Media Library (currently in backbone.js) and then batch sending images for alt text classifying~ {moved to #129}
~- [ ] error messaging or hook available to catch when ClassifAI doesn't match something for an image's alt text~ {moved to #139}
~- [ ] Automated captions~ {moved to #140}
~- [ ] Automated descriptions~ {moved to #141}

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related to #51.

**Comment by rickalee** [comment]
Would users have UI to to add their own tags along with automated ones?

**Comment by jeffpaul** [comment]
@rickalee the actual UX / UI hasn't been finalized, but I'll make note of your functionalities in the list of todos in the issue description as those seem like reasonable use cases... thanks!

**Comment by jeffpaul** [comment]
@rickalee if you take a look at @ryanwelcher's PR #125 you'll see that the tags does have a UI when you pull up the "Edit more details" part of an image in the Media Library.  That UI allows for users to add their own tags and remove automated ones.

**Comment by helen** [comment]
@jeffpaul Do we want to close this on this milestone and split what's left out into a new issue, or something else?

**Comment by jeffpaul** [comment]
@helen good call, done.
