### ISSUE TITLE
NLU credentials issue in v1.3

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#76]
**Describe the bug**
Getting Watson error in v1.3.0:
> Failed to classify content with the IBM Watson NLU API. Error: http_request_failed - A valid URL was not provided.

**Steps to Reproduce**

1. Update to version 1.3.0 with existing, functioning NLU credentials. 
2. Publish sample Post.
3. See error thrown after publishing (note error also occurs on All Posts table list view).

**Expected behavior**
Existing, functioning NLU credentials should continue to work post-upgrade.

**Screenshots**
none.

**Environment information**
 - Device: Mac mini (2018)
 - OS: MacOS 10.14.5 (18F132)
 - Browser and version: Firefox 67.0.1 (64-bit)
 - ClassifAI version: 1.3.0
 - Theme and version: Twenty Nineteen 1.4
 - Other installed plugin(s) and version(s): none.

**Additional context**
After going into the Language Processing settings and resaving the existing credentials, the error disappears and the NLU functionality returns to normal.

**Comment by helen** [comment]
Described this in technical terms in #86
