### ISSUE TITLE
Add Action & Filters to allow customization

### ISSUE THREAD

**Issue by dsawardekar** [10up/classifai#8]
We should add a few hooks/filters to allow developers to customize the plugin to better fit project needs. Potential areas include,

- [ ] Ability to change the Taxonomy Mapped to a Watson NLU feature.
- [ ] Ability to exclude classification of a Post.
- [ ] Ability to alter the results of the NLU API  call.
- [ ] Ability to change the terms that are associated with a post after classification.
- [ ] Ability to change the NLU feature matching threshold.

cc @helen @adamsilverstein

**Comment by adamsilverstein** [comment]
makes sense to me especially if we only use them once to run thru the filters.

**Comment by jeffpaul** [comment]
As we're looking to release v1.5.0 in the next week or so and with no linked PR for this issue, I'm going to move this to `1.6.0` until we're able to work up a PR for it.

**Comment by sudar** [comment]
@jeffpaul 

I am interested in working on this issue.

**Comment by ShahAaron** [comment]
@jeffpaul 

This issue was completed https://github.com/10up/classifai/pull/18

I've checked master branch and all the actions/ filters are there. They also have correct docblocks and appear on https://10up.github.io/classifai/

**Comment by jeffpaul** [comment]
Fantastic, thanks for digging in to validate @ShahAaron, it's greatly appreciated!
