### ISSUE TITLE
Add OpenAI provider for `Image Processing` > `Descriptive Text Generator` (aka image alt text)

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#826]
### Is your enhancement related to a problem? Please describe.

During a ClassifAI demo today, the Azure AI Vision alt text generated wasn't great across a couple specific examples for a prospective site's sample images.  In chatting with those folks it sounds like they've done some testing with ChatGPT and with a tweaked prompt have seen better results than what we were able to get back from Azure.  So, let's explore the options available with OpenAI (perhaps not just a specific GPT model if there's something OpenAI has that's tuned to computer vision functionality).

Things to look into as part of this:
* [Vision - OpenAI API](https://platform.openai.com/docs/guides/vision)
* [Introducing vision to the fine-tuning API](https://openai.com/index/introducing-vision-to-the-fine-tuning-api/)
* [Using GPT4o mini to tag and caption images](https://cookbook.openai.com/examples/tag_caption_images_with_gpt4v)

Let's also ensure that this works via the CLI command.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
I've already tested this before myself and using a vision model works fairly decently for this use case, though is more expensive I think than Azure.

We do already utilize the GPT4o mini model so would be fairly easy to add this as a new Provider for Descriptive Text Generation (and Image Tagging if we want)
