### ISSUE TITLE
Use provider classes for settings retrieval

### ISSUE THREAD

**Issue by helen** [10up/classifai#86]
Right now there are some functions in `Helpers.php` such as `get_plugin_settings()` that are out of date with the new settings structure after #46. I think this needs to only reference the top-level plugin settings in `ServicesManager::get_settings()` and the current usage replaced by actually referencing the appropriate `Provider::get_settings()` method (in this case, `NLU` because that was the original feature of this plugin).

This has caused one bug as of 1.3 - if you already had Watson NLU set up, you have to re-save settings for it to work because the polyfill contained in `Provider::get_settings()` only works for the actual display of the settings screen right now because it's not consistently used.

**Comment by JayWood** [comment]
Have some working replacements here for the `get_plugin_settings()` currently. Work is being done here: https://github.com/10up/classifai/commits/bug/nlu-credentials

Todo:
- [ ] Update code for update checker in main plugin file.
- [ ] Update test cases to accommodate new function signature.
- [ ] Update `reset_plugin_settings()` function.
- [ ] Update `set_plugin_settings()` function.

**Comment by JayWood** [comment]
For the `reset_plugin_settings()` I've added to the provider abstract to require each provider to have their own `reset_settings()` method. I've also updated each provider to have at least a blank method to prevent errors, as well as updating the NLU provider ( Watson ) to actually reset.

Looking into the set_plugin_settings() and test cases now.

**Comment by JayWood** [comment]
@helen or @jeffpaul I'm running out of available time here to handle the test cases, which is the _only_ location `set_plugin_settings()` is used. Even then, all test cases which use it are marked as skipped in the code.

I can open a PR for the current state of the branch, which resolves this issue and #76 if you'd like? I just need to know do you want me to target develop or master?

**Comment by jeffpaul** [comment]
@JayWood target develop please and thanks!

**Comment by helen** [comment]
Punting from 1.3.2 pending further review on other usage

**Comment by jeffpaul** [comment]
With no open PR for this and the fact that we're targeting v1.5 tomorrow, I'm going to punt this to v1.6 in hopes we can get this fully resolved then.

**Comment by ShahAaron** [comment]
@jeffpaul 

These changes were made in https://github.com/10up/classifai/pull/96. I can confirm they are all present in the master branch.

**Comment by jeffpaul** [comment]
@ShahAaron so you're confirming that the open todo's in https://github.com/10up/classifai/issues/86#issuecomment-505551491 are in fact resolved?

**Comment by ShahAaron** [comment]
@jeffpaul yes as set_plugin_settings() does not require any extra work as these are user settings so have no default to the provider classes
Also the tests which use it are therefore valid but they are skipped anyway.
