### ISSUE TITLE
wp cli commands aren't registered

### ISSUE THREAD

**Issue by aaronjorbin** [10up/classifai#91]
**Describe the bug**

When I attempt to run the wp-cli commands from the readme, I am told "Error: 'classifai' is not a registered wp command. See 'wp help' for available commands."

**Steps to Reproduce**

1. Install plugin
2. Activate Plugin and configure it
3. Run `wp classifai post`

**Expected behavior**

I expect my posts to be classified. 

**Screenshots**

**Environment information**
`
### wp-core ###

version: 5.2.3-alpha-45550
site_language: en_US
user_language: en_US
permalink: /%year%/%monthnum%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/daily.jorb.in
wordpress_size: 62.80 MB (65851314 bytes)
uploads_path: /var/www/daily.jorb.in/wp-content/uploads
uploads_size: 498.51 MB (522728770 bytes)
themes_path: /var/www/daily.jorb.in/wp-content/themes
themes_size: 225.70 MB (236661122 bytes)
plugins_path: /var/www/daily.jorb.in/wp-content/plugins
plugins_size: 74.46 MB (78080732 bytes)
database_size: 24.82 MB (26029248 bytes)
total_size: 886.30 MB (929351186 bytes)

### wp-active-theme ###

name: Twenty Nineteen
version: 1.4
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, infinite-scroll, jetpack-responsive-videos, jetpack-geo-location, jetpack-content-options, widgets
theme_path: /var/www/daily.jorb.in/wp-content/themes/twentynineteen

### wp-plugins-active (19) ###

Akismet Anti-Spam: version: 4.1.2, author: Automattic
AMP: version: 1.2.0, author: AMP Project Contributors
BRAD: version: 0.1.0, author: Aaron Jorbin
Caxton: version: 1.9.0, author: PootlePress
ClassifAI: version: 1.3.1, author: 10up
CoBlocks: version: 1.10.0, author: GoDaddy
Glue for Yoast SEO & AMP: version: 0.4.3, author: Joost de Valk
Google Analytics for WordPress by MonsterInsights: version: 7.7.1, author: MonsterInsights
Gutenberg: version: 5.9.2, author: Gutenberg Team
Hello Aaron: version: 1.6, author: Aaron Jorbin
Hello Brainstorm: version: 1.6, author: Aaron Jorbin
Hello Dukakis: version: 1.6, author: Aaron Jorbin
Insert Headers and Footers: version: 1.4.4, author: WPBeginner
Jetpack by WordPress.com: version: 7.4.1, author: Automattic
Log Deprecated Notices: version: 0.4.1, author: Andrew Nacin
WordPress Beta Tester: version: 2.0.4, author: Peter Westwood, Andy Fragen
WP-DraftsForFriends: version: 1.0.2, author: Lester 'GaMerZ' Chan
WP REST API Menus: version: 1.3.1, author: Fulvio Notarstefano
Yoast SEO: version: 11.4, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 4 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 4 GB
	imagick::RESOURCETYPE_MEMORY: 2 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: not available
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 3.13.0-52-generic x86_64
httpd_software: Apache/2.4.18 (Ubuntu)
php_version: 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 64M
php_post_max_size: 64M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.3.13-MariaDB-1:10.3.13+maria~xenial
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/daily.jorb.in/wp-content
WP_PLUGIN_DIR: /var/www/daily.jorb.in/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
`

**Comment by jeffpaul** [comment]
@aaronjorbin I believe you'll need to provide at least one post ID (or a list of them).  Can you give that a try?

**Comment by aaronjorbin** [comment]
@jeffpaul Nope, doesn't help.

**Comment by jeffpaul** [comment]
@ryanwelcher @helen I wonder if when we restructured the settings to add in Azure if we renamed something such that https://github.com/10up/classifai/blob/develop/includes/Classifai/Command/ClassifaiCommand.php references an old spelling/location for something?  I'll dig through that to see if I can find something, let me know if you have other avenues to help triage.

**Comment by jeffpaul** [comment]
Maybe this: [Register a command to WP-CLI](https://make.wordpress.org/cli/handbook/internal-api/wp-cli-add-command/).

**Comment by JayWood** [comment]
This has to be fixed as part of #86 anyhow since there are functions which need testing being used there within the CLI script. I'll snag this and see if I can squeeze it in.

**Comment by JayWood** [comment]
Fixed above 🎉
