### ISSUE TITLE
Duplicate notification when saving Registration Key

### ISSUE THREAD

**Issue by eflorea** [10up/classifai#99]
**Describe the bug**

When saving settings for the Classifai plugin (Registration Email and Registration Key) there is a duplicate notification: "Settings saved."

**Steps to Reproduce**

1. Go to ClassiAi settings -> wp-admin/options-general.php?page=classifai_settings
2. Save settings
3. See duplicate notification

**Screenshots**

![Screen Shot 2019-07-12 at 10 14 45 AM](https://user-images.githubusercontent.com/13055601/61146073-f3d9ec00-a48d-11e9-848f-ba32d49172b8.png)

**Comment by jeffpaul** [comment]
@eflorea thanks for the feedback!  Can you confirm if you had already input credentials for the Language or Image Processing settings pages as well or just the main ClassifAI Settings page?

**Comment by dinhtungdu** [comment]
The duplicated notice causes by the wrong setting page in the older version of ClassifAI. When #166 is merged, this is will be solved automatically.
